### PR TITLE
Adds pushbullet indicator icons

### PR DESCRIPTION
**Pull request by wa4557**
status icons for pushbullet indicator

### CODE REVIEW

**Comment by Foggalong** [comment]
Doesn't it need to go into the Light and Normal theme rather than being labelled Dark and Light?

**Comment by wa4557** [comment]
No. I don't think so. It's the same as with variety for example. This one needs both variants in both themes and since numix-light inherits numix it's only needed in numix

**Comment by bil-elmoussaoui** [comment]
For variety and touchpad indicator @dirtydancing have created just a symlink from Numix-Light to the icons in Numix, can you do the same thing?

**Comment by wa4557** [comment]
No he hasn't. Variety or touchpad-indicator icons are solely in Numix

**Comment by bil-elmoussaoui** [comment]
Well, this has been merged nop? [https://github.com/numixproject/numix-icon-theme/pull/457](Indicator light dark)

**Comment by wa4557** [comment]
Yes but this one too: #487

**Comment by bil-elmoussaoui** [comment]
Ops:p Sorry i haven't seen this

**Pull request merged**
