### PR TITLE
Fixes #331

### LINKED ISSUE #331: Additional percentage level battery status icons in fixed size directories 16, 22 and 24
Following-up on my comment over at https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-76519738, I have done some testing with the additional percentage battery status icons introduced for Ubuntu 15.04 for 10%, 30%, 50%, 70%, 90%:

These (tested with testing battery icons size 22x22) are already working in current daily Ubuntu 15.04, and at the same time they do not cause any breakage in Ubuntu 14.10, which simply does not pick up these additional battery status icons. Also tested against elementary OS Freya Beta 2, based on Ubuntu 14.04 LTS: just like in Ubuntu 14.10, the additional battery status icons simply do not get picked up.

These additional icons are useful because they provide a finer granulation, and because they address the issue of a too early warning status with the present icons, cf. bug report at https://bugs.launchpad.net/ubuntu-ux/+bug/1388235.

Screenshots when tested simultaneously against Ubuntu 14.10 (above) and Ubuntu 15.04 (VM, below):

battery_28

battery_20

battery_14

battery_9

battery_4

battery_charging-2

battery_charging-5

battery_charging-21

battery_charging-35

battery_charging-90

This is how these additional battery status icons (10%, 30%, 50%, 70%, 90%) could be fit into the present ones, which in this overview have been left untouched (additionally all selected for visual contrast).

battery-new-levels

battery-new-levels2

I would create a pull request for these myself, but I am not yet very familiar with Inkscape (for the icon overview above I just scaled the already existing bars, which of course does not work for the charging status battery icons).

@wa4557 Are you interested in contributing these? For bar height in the screenshots above, I used px (new sizes bold) **2,5** orange - 4 orange - **5,5** - 7 - **8,5** - 10 - **11,5** - 13 - **14**. In addition, the battery icons seem to use #dedede instead of #dcdcdc, so this might be an opportunity to make these consistent as well. From my perspective, adding these battery status icons makes sense even if there is a status icons redesign in the future, because this establishes a baseline on which such redesign could build upon.

The additional battery status icons in question here are marked yellow in this overview:

ca8cdf3c-bf37-11e4-8d9b-a2d16276d471

### PR DESCRIPTION
**Pull request by wa4557**
Adds more percentages for the battery icons cf. #331 
Already new design, for 16x16 22x22 24x24 for light and dark theme

### CODE REVIEW

**Comment by dirtydancing** [comment]
Wow, faster than fast, and already in the new design :-) Great!

Two points:

1) I noticed that there are 58 files changed, but it should be 60. Any reason why in `Numix-Light/16x16/status`, `battery-010.svg` and `battery-090-charging.svg` are missing?

2) Bonus request: could you add the gpm-battery symlinks (`gpm-battery-...` symlink with the target `battery-...`) for each of these new icons, as listed in the overview below? The symlinks further down are not needed for these additional icons at the moment, as far as I can tell. Let's go with the gpm-battery symlinks for now.

This only applies to Numix, not to Numix-Light (consistency also here, in Numix-Light all of these symlinks do not exist as of now anyways, iirc).

symlinks_gpm-battery

**Comment by wa4557** [comment]
1) No just missed them, added
2) done

**Comment by dirtydancing** [comment]
Thanks!

**Comment by dirtydancing** [comment]
Updated overview over at https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-87110450

**Comment by Foggalong** [comment]
I have to leave that page to load all the images for a few minutes now because otherwise it just jumps around making it unreadable :P

**Comment by dirtydancing** [comment]
Yeah, I can confirm the loading time for that page :-)

**Pull request merged**
