### PR TITLE
Adds online-account apps, removes several pngs

### PR DESCRIPTION
**Pull request by wa4557**
Those are all the non circular app icons that used to be in circle. I cleaned them and aligned them and put them in base. A lot of png icons (all those `im-*`) were replaced by symlinks to these new icons. I added them up to `48x48`

### CODE REVIEW

**Comment by Foggalong** [comment]
what happened to `im-nov.svg`? Is it not used anymore?

**Comment by wa4557** [comment]
Oh damn, I forgot that one. Have to design an icon for that. Did the same thing for `icq` btw.

**Comment by wa4557** [comment]
Do you know from which application this icon is/was?

**Comment by Foggalong** [comment]
aw, thanks! honestly have no idea. thing it's from before I started contributing

**Comment by wa4557** [comment]
Ok I added an icon. Was obviously novell messenger oO

**Pull request merged**
