### PR TITLE
Maintenace for scalable icons

### PR DESCRIPTION
**Pull request by wa4557**
Same treatment for scalable icons. Together with the maintenance for the places icons and all the maintenance PRsThe filesize reduction is roughly 40MB. So quite a bit :)

### CODE REVIEW

**Comment by Foggalong** [comment]
@wa4557 `Numix-Light/scalable/places/user-home-symbolic.svg` seems to have been borked

**Comment by wa4557** [comment]
Fixed

**Comment by wa4557** [comment]
@Foggalong Can you copy the icons from `numix-folders` to here as well? That's actually the part where most of the filesize reduction is possible...

**Comment by Foggalong** [comment]
Sure thing :)

**Pull request merged**
