### PR TITLE
Adds stock_signature.svg

### PR DESCRIPTION
**Pull request by wa4557**
I think it looks good and fits with the rest of the status icons, but I'm not 100% sure

### CODE REVIEW

**Comment by Foggalong** [comment]
Can you add the icons for `stock_signature-ok` and `stock_signature-bad` too? Just needs to be a tick/cross in the bottom right corner

**Comment by wa4557** [comment]
Sure. Was just waiting for your verdict

Joshua Fogg <notifications@github.com> schrieb am Di., 23.06.2015, 23:34:

**Comment by Foggalong** [comment]
:+1:

**Comment by wa4557** [comment]
Fine, done

**Pull request merged**
