### PR TITLE
two symlinks for geary

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
#768  
- close-symbolic
- format-text-remove-symbolic

### CODE REVIEW

**Comment by palob** [comment]
Do you know where ``close-symbolic`` is used?

**Comment by bil-elmoussaoui** [comment]
No idea :p

**Comment by palob** [comment]
Could you check if it is the ``X`` in window headerbars?
If it is the symlink will introduce visual inconsistency there.

**Comment by bil-elmoussaoui** [comment]
Nop not used at all! i got the icons from the source code

**Comment by palob** [comment]
Yeah, you're right. It isn't included in Adwaita.
And as far as I can see the Numix ``window-close-symbolic`` looks the same as the Adwaita one.

**Pull request merged**
