### PR TITLE
changing the spotify-client name to spotify-indicator

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Well , we now support spotify indicator icon in Hardcode-Tray fixer. But the icons that is used is 
spotify-panel (from the Numix-Circle in scalable) we decided to change the name to avoid this conflict

### CODE REVIEW

**Comment by Foggalong** [comment]
Is `spotify-client.svg` not the icon that's used in the Status are in some cases?

**Comment by wa4557** [comment]
Yeah, but it's also the name in circle, so this has to be changed anyway at some point. But yes symlinks are probably a better idea

**Comment by bil-elmoussaoui** [comment]
My bad, i wrote ```spotify-panel.svg``` instead of ```spotify-client.svg```

**Comment by wa4557** [comment]
@bil-elmoussaoui You're mixing some things here aren't you?

**Comment by bil-elmoussaoui** [comment]
@wa4557 nop :p in the description i wrote " the icons that is used is spotify-panel " instead of spotify-client. and this icon is the same as the application icon and as this icon is in the ```scalable``` folder in Numix Circle this icon is used by Hardcode Tray instead of 22 or 24 size

**Comment by wa4557** [comment]
That's not what I mean :) You're also symlinking something in devices in this Pull request :P

**Comment by bil-elmoussaoui** [comment]
Ah :S the icons in devices are for #124 @Foggalong this can be merged like that o i have to separate them ?

**Comment by Foggalong** [comment]
Separating them is needed. I don't have time to verify the pull request just yet :(

**Comment by bil-elmoussaoui** [comment]
Okay :P i'm closing this then

**Pull request closed without merging**
