### PR TITLE
Adds new teamviewer icons

### PR DESCRIPTION
**Pull request by wa4557**
Teamviewer is now a native linux app (yay), and uses only one panel icon for now. Added them

### CODE REVIEW

**Comment by Foggalong** [comment]
If Linux file names weren't case sensitive we wouldn't be able to merge this because the app icon name is `teamviewer.svg` :sweat_smile:

**Comment by bil-elmoussaoui** [comment]
Are you sure about this?  In my case, using teamviewer beta, the icon still doesn't look correctly. 
screenshot from 2017-12-25 13-43-14
screenshot from 2017-12-25 13-42-57

**Comment by wa4557** [comment]
Yes you're right. I guess we have to move them to the `panel` folder

**Comment by bil-elmoussaoui** [comment]
@wa4557 I don't think it the icon is not hardcoded. all the icons are links to /opt/teamviewer/tv_bin/desktop. If you replace those icons there, nothing changes at all :( 
+ The TeamViewer is the new icon name for the application itself.

**Comment by wa4557** [comment]
In my case, when put the icon in the panel folder everythings fine. The app icon is shown in the launcher, the monochrome icon in the tray... Maybe it's different in GNOME?

**Pull request merged**
