### PR TITLE
Fixes #1046

### LINKED ISSUE #1046: Gnome-Foot on budgie-desktop
The Gnome-Foot icon for the start menu button (top left) - was this intentional or is this a missing icon?

### PR DESCRIPTION
**Pull request by wa4557**
#1046

### CODE REVIEW

**Comment by HEXcube** [comment]
@wa4557 Do u mind if I ask, but isn't `Numix/scalable/places/start-here-symbolic.svg` 's color supposed to be `#bebebe` instead of `#bdbdbd`? I thought they won't work if the color is different :confused:

**Comment by wa4557** [comment]
Sure. Thanks for finding

**Comment by Foggalong** [comment]
Curious where the new design came from?

**Comment by wa4557** [comment]
You dislike? One I came up with...

**Comment by Foggalong** [comment]
Not at all, [was just comparing it to the existing one](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/16/places/start-here.svg). It's quite a cool take on the idea!

**Comment by wa4557** [comment]
Yeah I have my moments :)

**Comment by Foggalong** [comment]
@wa4557 if you fancy changing the others to match your design too, feel free :)

**Comment by wa4557** [comment]
Alright, pushed :+1:

**Pull request merged**
