### PR TITLE
Bunch of symbolic icons for Adwaita

### PR DESCRIPTION
**Pull request by wa4557**
from #577

### CODE REVIEW

**Comment by Foggalong** [comment]
We might have a Circle icon whos symbol could be used for `camera-video-symbolic.svg`

**Comment by wa4557** [comment]
Was actually looking before I tried to make the icon but the only one close was `screen-recorder` and this one doesn't really qualify as a good icon...

**Comment by Foggalong** [comment]
Thinking about it, I think of a lot of the "video" type apps use the film-tape symbols rather than camera symbols. Happy with this :+1:

**Comment by wa4557** [comment]
We might revisit it as soon as `camera-video.svg` will be added...

**Comment by Foggalong** [comment]
:+1:

**Pull request merged**
