### PR TITLE
Small fix to index.theme

### PR DESCRIPTION
**Pull request by wa4557**
Because the places folders are special

### CODE REVIEW

**Comment by Foggalong** [comment]
Wouldn't actions be the same too?

**Comment by wa4557** [comment]
Nope, actions are just like all the other folders. Except that there are also bigger sizes, but they do not interfere...

**Comment by Foggalong** [comment]
Ah, I think I'm misunderstanding what this one does then

**Comment by wa4557** [comment]
This is because for `places` `48` doesn't need to cover `96` because there is a seperate and complete folder for this size. Thus `48` only needs to cover sizes up to `63px`

**Comment by Foggalong** [comment]
We have the same for actions with the 96px folder too, no? Does it not matter that even of few such icons exist?

**Comment by wa4557** [comment]
But for actions there are just a few icons in the `96px` folder (the icons with folders in it), all the other icons should be scaled up versions from `48`. This means we cannot change the maxsize variable for these folders

**Comment by wa4557** [comment]
Actually the fix in this PR is just a cosmetic one, because no matter what this variable is, the correct icon is used

**Comment by Foggalong** [comment]
Ah, okay :)

**Pull request merged**
