### PR TITLE
add new humanity symlinks

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Added symlinks for #826  : 
 - stock_music-library.svg
 - cab_extract.svg
 - application-install.svg
 - audio-volume-muted-blocked-panel.svg
 - dialog-info.svg
 - gnome-fs-bookmark.svg
 - gtk-dialog-warning-panel.svg
 - messagebox_info.svg
 - stock_bookmark.svg
 - stock_dialog-error.svg

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
@Foggalong can you take a look at this one? again my fork is really a mess haha! and i have some PR ready to be merged ;)

**Comment by Foggalong** [comment]
How have you messed up your fork again? :P I'll give it a look over

**Comment by Foggalong** [comment]
Looks good to me :+1:

**Comment by bil-elmoussaoui** [comment]
As always :p Thanks

**Pull request merged**
