### PR TITLE
Adds mathematica mimetypes

### LINKED ISSUE #294: Mimetype request Mathematica .nb
A mimetype for mathematica (scientific computational software) notebook-files (.nb) would be great:

application/mathematica

### PR DESCRIPTION
**Pull request by wa4557**
Adds mimetypes for mathematica fixes #294 

Suggestions?
application-mathematica

### CODE REVIEW

**Comment by palob** [comment]
A red background + monochrome icon without the inner lines?
I think it's too detailed to be consistent with the existing ones.
Does it scale well?

**Comment by wa4557** [comment]
More like this?
application-mathematica


Idk, you're definitely right but it looked better before

**Comment by wa4557** [comment]
Scaling is ok, btw.

**Comment by palob** [comment]
Hmm, it's hardly recognisable this way. But I don't think the first one meets the guidelines.
How about a red icon (the sheet) background + white icon + transparent lines (i.e. only the rhombs in white)?

**Comment by wa4557** [comment]
I like that one, although its still kind of detailed, but way better than before
application-mathematica

**Comment by palob** [comment]
:+1: Much better indeed.

**Comment by palob** [comment]
Miiiinor issue: There is invisible cruft/leftovers underneath the symbol. Makes for a bit bigger files.

**Comment by Foggalong** [comment]
Is there anything that can be done about that?

**Comment by palob** [comment]
Manually deleting. But it isn't crucial.

**Comment by Foggalong** [comment]
Am I okay to merge then? :)

**Comment by wa4557** [comment]
I delete the leftovers, wait for my next commit, then you can merge

**Comment by palob** [comment]
I'm dead chuffed :laughing:

**Pull request merged**
