### PR TITLE
Added mimetype for D language source files

### PR DESCRIPTION
**Pull request by palob**
text-x-dsrc

### CODE REVIEW

**Comment by Foggalong** [comment]
Some thing looks a little off about the icon and I can't put my finger on it. Maybe try an openSans D instead?

**Comment by palob** [comment]
Will fiddle about a bit later.

**Comment by Foggalong** [comment]
Sure thing!

**Comment by palob** [comment]
Two new letter styles:
bold
normal

**Comment by Foggalong** [comment]
Go bold :)

**Comment by palob** [comment]
Bold letters pushed!

**Pull request merged**
