### PR TITLE
Fixes qt icon lookup failure

### PR DESCRIPTION
**Pull request by wa4557**
And another one. @Foggalong Can you take a look at this. I know there are a lot files, but there's not really a lot that is changed. Removing the `places` icons from `96`,`256` and `128` also makes future development easier (They are really nothing else than upscaled versions from `64` and `48`)

### CODE REVIEW

**Comment by Foggalong** [comment]
I'll try and get this looked at asap :+1:

**Comment by wa4557** [comment]
Proof that the `96` `128` and `256` are redundant
96px
test
48px
test

64px
test
128px
test
256px
test


And this is the same for all styles (6 is the most complicated anyways). So really this should be merged.

**Comment by Foggalong** [comment]
Sorry for the delay on this, thought I'd merged it ages ago :flushed:

**Comment by wa4557** [comment]
Don't worry, but you have to merge the corresponding folder PR as well :)

**Pull request merged**
