### PR TITLE
Fixes #791

### LINKED ISSUE #791: Gnome shell search - Weather and Contacts
I don't know if this belongs in numix or numix-circle, but the fact is that over-sized, blurred monochrome icons are being displayed on gnome-shell with weather and contact search results:

Default icon theme (Adwaita):

screenshot from 2015-10-18 13-09-05
screenshot from 2015-10-18 13-08-51

Numix icon theme:

screenshot from 2015-10-18 13-08-28
screenshot from 2015-10-18 13-08-09

The displayed icons should be big, colored icons, such as this search result:

screenshot from 2015-10-18 13-13-24

### PR DESCRIPTION
**Pull request by wa4557**
Weather status icons for bigger sizes + avatar-default #791

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
I would prefer to have a colored avatar icon!

**Comment by palob** [comment]
Something like from the 4th foto in the ``image-gallery.svg`` action icon?

**Comment by wa4557** [comment]
Well it's still a status icon, they are usually simpler...

**Comment by Foggalong** [comment]
Yeah, not sure why we'd make the status icons colourful?

**Comment by bil-elmoussaoui** [comment]
is avatar-default a status icon?

**Comment by wa4557** [comment]
because they are not tray icons, but used in other places

**Comment by Foggalong** [comment]
Oh wait, I'm confused now. Are these the ones that appear next to a temperature/weather summary in the launcher?

**Comment by wa4557** [comment]
Yeah

**Comment by Foggalong** [comment]
And do they use all the same names as the current weather indicators? (think they could be picked up accidentally)

**Comment by wa4557** [comment]
That's why I added only sizes >= 32px

**Comment by Foggalong** [comment]
Cool :+1: Do Numix-Light variants make sense for these icons based on where they're used? I'm not really a GNOME user

**Comment by wa4557** [comment]
I guess not (I'm not a gnome user neither) I've never seen a light dash. @bil-elmoussaoui ?

**Comment by bil-elmoussaoui** [comment]
@wa4557 @Foggalong they're not needed ! this can be merged

**Comment by Foggalong** [comment]
Coolio :+1:

**Pull request merged**
