### PR TITLE
First bunch of libreoffice symlinks

### PR DESCRIPTION
**Pull request by wa4557**
First ones from #1038. Those were the ones where a symlink is possible. Less than I hoped, for the other ones we need to design distinct icons :(

```
lc_aligncenter.svg            lc_crop.svg             lc_italic.svg
lc_alignhorizontalcenter.svg  lc_decrementindent.svg  lc_mergecells.svg
lc_alignleft.svg              lc_deletecolumnds.svg   lc_sortascending.svg
lc_alignright.svg             lc_deleterows.svg       lc_sortdescending.svg
lc_bold.svg                   lc_incrementindent.svg  lc_underline.svg
```

### CODE REVIEW

**Comment by palob** [comment]
Do they show up without further action?

**Comment by wa4557** [comment]
Unfortunately not. But I guess we have to add them beforehand and think about implementation afterwards

**Comment by bil-elmoussaoui** [comment]
Some of LibreOffice icons can be used here #871 too

**Comment by Foggalong** [comment]
> lc_deletecolumnds.svg

That last d needs to go.

**Comment by bil-elmoussaoui** [comment]
Shouldn't we create/use a new repo for the libreoffice theme? i don't think it's a good idea to have those icons here too. Maybe the icons that are missing in Numix theme, yeah.

**Comment by Foggalong** [comment]
They're alright in here for now until we know exactly how we want to build the theme

**Comment by wa4557** [comment]
Fixed :+1:

**Pull request merged**
