### PR TITLE
Adds cursor theme

### LINKED ISSUE #949: Numix cursor theme
I've started working on a Numix cursor theme (not finished yet) but some icons are already in a good shape (the first 6 for example, the rest is not from me yet). https://github.com/wa4557/numix-cursor-theme/tree/master/build/dark/x2

If this is finished this is something that could be added to the base theme, since a cursor-theme is the one thing that's still missing for a perfect numix-desktop. You think this is something?

### PR DESCRIPTION
**Pull request by wa4557**
Adds support for cursor theme, fixes #949. Again: to you want this repo as well https://github.com/wa4557/numix-cursor-theme ?

### CODE REVIEW

**Comment by nfnty** [comment]
Any progress on smaller sizes?

Shouldn't the SVG files also be included? In case anyone wants to rebuild.

**Comment by wa4557** [comment]
@nfnty 
I could make just render smaller sizes from the already existing icons; I'm not sure though that this would result in blurry cursor icons, have to try that out. 

Concerning svgs: They are in the original repo + build instructions

**Comment by nfnty** [comment]
Any updates?

**Comment by Foggalong** [comment]
@wa4557 Sorry for the delay on this! Happy to receive the transferred repo so that the cursor theme can live there :)

**Comment by wa4557** [comment]
Cool. How can I do that?

**Comment by Foggalong** [comment]
@wa4557 Settings, down to the bottom and click transfer repo and the user to transfer to is "numixproject" :)

**Comment by wa4557** [comment]
Nope, that doesn't work: You don't have admin rights for "numixproject"

**Comment by bil-elmoussaoui** [comment]
@wa4557 Try by adding @Foggalong as a collaborator to your repo so he can do the transfer too

**Comment by Foggalong** [comment]
Being added as a collaborator isn't bringing up a settings menu for me so I'm just gonna do a good ol' fashioned repo merge. Will report back once done :)

**Comment by nfnty** [comment]
Nice!

@wa4557 Any progress on smaller sizes?

**Comment by wa4557** [comment]
@nfnty Working on it, but it is a lot of work. I'm a bit busy lately, but I'll get eventually around doing it.

@Foggalong Nice. You still need to merge this PR though, otherwise noone will get them :)

**Comment by Foggalong** [comment]
@wa4557 I'll see if we can't set up a separate PPA package for the cursor themes so there's no worry about adding them into the icon theme :)

**Pull request closed without merging**
