### PR TITLE
Adds correct everpad/evernote status icons

### PR DESCRIPTION
**Pull request by wa4557**
The status icons from everpad.svg evernote.svg and everpad-panel.svg had the wrong size in 22x22/status (24x24 pixels) and were just a symlink to the one in 24x24/status. I added correctly sized status icons in 22x22/status and added the missing icons in 24x24/status

### CODE REVIEW

**Comment by Foggalong** [comment]
Check your icons, they're showing up as blank for me
screenshot - 270315 - 18 39 20

**Comment by wa4557** [comment]
Argh, inkscape does that sometimes...

**Comment by Foggalong** [comment]
I'm not 100% certain, but I think if it's like that it will not display correctly in some DEs. Maybe try doing some non-meaningful fiddles (changing grid, camera location, etc) and then saving again?

**Comment by wa4557** [comment]
No chance to make them show up.. I'll fix this tomorrow

**Comment by wa4557** [comment]
Saving as pdf and converting this pdf to svg did the trick...

**Comment by Foggalong** [comment]
Oh inkscape.

**Pull request merged**
