### PR TITLE
Add haguichi indicator(s)

### PR DESCRIPTION
**Pull request by leoheck**

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
You need to add the Numix-Light version too

**Comment by leoheck** [comment]
Ok

**Comment by bil-elmoussaoui** [comment]
Plus 16/24 sizes too :+1:

**Comment by wa4557** [comment]
I'll fix this now, since there was no activity for a long time

**Comment by wa4557** [comment]
Added missing sizes and icons for numix-light

**Pull request merged**
