### PR TITLE
Electron tray icons

### PR DESCRIPTION
**Pull request by wa4557**
A bunch of tray icons from #1107

### CODE REVIEW

**Comment by Foggalong** [comment]
All good apart from the following:

* Replace `nylas-tray-newitems.svg` with `nylas-tray-full.svg`  and move `nylas-tray-empty.svg` to `nylas-tray-full.svg`. Then create a new icon which is a transparent version of `nylas-tray-full.svg` and name it  `nylas-tray-empty.svg`. This allows for distinction between new items and a full tray.
* What's the distinction between highlight and unread in Slack? I'm not familiar with that program

**Comment by wa4557** [comment]
Check on the `nylas` icons, will push that asap

Messaging app. Numix does not differentiate between `unread` and `highlight` so I guess using the same icon is fine. I could use the warning orange though?!

**Comment by Foggalong** [comment]
Nah, keep them both blue for Slack :)

**Comment by wa4557** [comment]
Pushed

**Pull request merged**
