### PR TITLE
Adds missing dropbox emblems

### LINKED ISSUE #893: Dropbox missing emblems
Theres two missing emblems icon for Dropbox
The first one is used for application that have permission to sync files to your Dropbox account
- [ ] emblem-dropbox-app
- [ ] emblem-dropbox-selsync

capture du 2015-11-21 00-05-06

### PR DESCRIPTION
**Pull request by wa4557**
Fixes #893

### CODE REVIEW

**Comment by Foggalong** [comment]
I'm not entirely sure on the dropbox-app one. Isn't this for dropbox plugins rather than the dropbox app?

**Comment by wa4557** [comment]
Probably true, yes. I'll change that asap!

**Comment by Foggalong** [comment]
:+1:

**Comment by wa4557** [comment]
Changed :)

**Comment by bil-elmoussaoui** [comment]
Looks fine :) Thanks!
capture du 2015-11-22 21-18-30

**Pull request merged**
