### PR TITLE
Adds google drive folder icons

### PR DESCRIPTION
**Pull request by wa4557**
Since we are hopefully getting an official goolge drive client for linux (fingers crossed: http://www.webupd8.org/2015/01/official-google-drive-linux-client.html), I thought it is necessary to have the proper places icons...

### CODE REVIEW

**Comment by Foggalong** [comment]
Seems like a cool addition, but do we how do we know what the icon name will be?

**Comment by bil-elmoussaoui** [comment]
if so , you can support more folders like steam folder or virtualbox mks foldr?

**Comment by Foggalong** [comment]
Plan is to add a few more folder types, so feel free to request some in separate issues. The above question was more out of curiosity than a demand

**Comment by wa4557** [comment]
Nope, we don't know yet, but symlinking should be the smallest problem :)

**Comment by Foggalong** [comment]
We decided to go with a slightly different symbol and had to set it all up in the [Numix Folders](https://github.com/numixproject/numix-folders) repo rather than here. However, I'm gonna merge this in and then make another pull to revert it so that you get credit for your hard work. Seriously - thank you :) We wouldn't have done a Google Drive icon without you!

**Pull request merged**
