### PR TITLE
sharedlib mimetype - Fixes #557 #559

### LINKED ISSUE #557: Mimetype: application/x-sharedlib
Name: **shared library**
Mimetype: **application/x-sharedlib**
Possible extensions: **.so**

Description: **Library file**

image

### PR DESCRIPTION
**Pull request by hlechner**
Fixes #557 #559 

imageimageimageimageimageimage

**Alternatives:**
22/24:
imageimage
16:
imageimage

**Description:** The design idea came from [here](https://github.com/hlechner/hl-numix-mime/issues/6).

### CODE REVIEW

**Comment by wa4557** [comment]
I would go for alternative 1 for 22/24

**Comment by hlechner** [comment]
Oh, I misunderstood your suggestion before.

Fixed.

**Comment by wa4557** [comment]
:+1: It's not me though making these decisiions :)

**Comment by hlechner** [comment]
the mimetype ``application/x-sharedlib`` are also reported in #580

**Comment by Foggalong** [comment]
It's not 100% on the guidelines because it uses multiple colours, but close enough that I'll let it pass :)

**Pull request merged**
