### PR TITLE
virtualbox mimetypes

### LINKED ISSUE #859: Mimetypes: Virtualbox files
Below you can see the mimetypes added into hicolor theme by virtualbox program:
image

Example:
image

> standard::symbolic-icon: virtualbox-vbox-symbolic, application-x-virtualbox-vbox-symbolic, application-x-generic-symbolic, **virtualbox-vbox**, application-x-virtualbox-vbox, application-x-generic

- [ ] virtualbox-vbox (VirtualBox Machine Definition)
- [ ] virtualbox-extpack (VirtualBox Extension Pack)
- [ ] virtualbox-ova ([Open Virtual Appliance](https://en.wikipedia.org/wiki/Open_Virtualization_Format))
- [ ] virtualbox-ovf ([Open Virtualization Format](https://en.wikipedia.org/wiki/Open_Virtualization_Format))

Disk Files:
- [ ] virtualbox-vdi ([Virtual Disk Image](https://en.wikipedia.org/wiki/VirtualBox#VirtualBox_Disk_Image))
- [ ] virtualbox-vhd ([Virtual Hard Disk](https://en.wikipedia.org/wiki/VHD_(file_format)))
- [ ] virtualbox-vmdk ([Virtual Machine Disk](https://en.wikipedia.org/wiki/VMDK))
- [ ] virtualbox-hdd (Virtual Hard Disk)

### PR DESCRIPTION
**Pull request by hlechner**
imageimageimageimageimageimageimageimage
imageimageimageimageimageimageimageimage
imageimageimageimageimageimageimageimage
imageimageimageimage
imageimageimageimage
imageimageimageimage

Fixes #859 
Fixes hlechner/hl-numix-mime#3

Credits to @wa4557 for the design idea.

Further Details: [here](https://github.com/hlechner/hl-numix-mime/issues/3)

### CODE REVIEW

**Comment by Foggalong** [comment]
I like the idea, but why have you changed the colours from those used in the original icons?

**Comment by hlechner** [comment]
I'm a virtualbox user for some years now, the virtualbox idea of each file need a different color is definitely not good.

It is confusing because there are 8 different colors and some similar. Inside the program itself doesn't have any color reference.

There are just 2 important files that should be on the same colors as original ones:
Vbox (blue) - it's a virtual machine itself
VDI (red) - it's a default HD format of virtualbox.

so, instead of having a confusing colors a put a colors by group.
vbox [blue] . (original)
ext [green] . (original)
vdi,vhd,vmdk,hdd [red] - it's a lot more intuitive
ova,ovf [purple] - the original one is orange/yellow, too close to red, thats why i choose a different color.

as virtualbox user I really think the group color is best option than 8 different colors

**Comment by hlechner** [comment]
imageimageimageimageimage

As @palob suggestion I've fixed some 32px that was blurry

**Comment by Foggalong** [comment]
Ah, I guess that's fair enough. Are vdi,vhd,vmdk,hdd all different types of the same format then?

**Comment by hlechner** [comment]
The format it's different but it's for the same purpose. all of them (vdi,vhi,vhd,vmdk,hdd) are to store the Hard Disk into a file.

**Comment by Foggalong** [comment]
Awesome, happy to go with that then :)

**Comment by hlechner** [comment]
Sanity check:
```
grep -R -wi "stroke:#" * | grep -v "@2" | grep mimetypes
grep -R -wi "ellipse" * | grep -v "@2" | grep mimetypes
```
**OK**, nothing found

**Pull request merged**
