### PR TITLE
Add icons for clementine

### PR DESCRIPTION
**Pull request by varlesh**

### CODE REVIEW

**Comment by Foggalong** [comment]
Thanks for the contribution, is this for fixing #273? There are a few things that need changing though:

* All the icons & symlinks need to go in all the sizes
* The symlink you chose for `edit-clear-locationbar-ltr.svg` doesn't fit with the existing icon for `edit-clear-locationbar-rtl.svg`
* `x-clementine-artist.svg` should be a symlink rather than a SVG
* `view-media-playlist.svg` and `view-media-lyrics.svg` feel like they'd be better suited to being standalone icons with a bit more detail.

**Comment by varlesh** [comment]
Why all size? Used only 16x16 and 22x22
I don't know why developers used edit-clear-locationbar-ltr. I know edit-clear-locationbar-ltr have other style (see symbolic icon), but this icon not good looking on clementine.

x-clementine-artist - i don't find analog icon and create new icon. Exist only categories/preferences-desktop-personal-directory, but this icon have another size 10x11

symlink - it's easy way )) Maybe create new icons for playsit and lyrics.

**Comment by Foggalong** [comment]
* Larger sizes are used in HiDPi, XHiDPi, etc and could also be used by other applications
* If the name & context indicates the icon should be a certain way then that's the way we do it. If you think the Clementine develops picked the wrong icon though then report it to them and they might change it
* Ah, in that case okay.
* Symlinks are easier yeah, but why do it if it doesn't make sense in the context?

**Comment by varlesh** [comment]
Again HDPI, i can not hide from it! 
If anybody create new icons for playlist and lyrics I'm not against.

**Comment by varlesh** [comment]
for lyrics?

**Comment by varlesh** [comment]
or this

**Comment by Foggalong** [comment]
The latter would be good :)

**Comment by varlesh** [comment]
for playlist?

**Comment by varlesh** [comment]
or this

**Comment by varlesh** [comment]
Also change multimedia-player-ipod-mini-blue (from yourself).
final result

**Comment by varlesh** [comment]
I commited, you decide.

**Comment by varlesh** [comment]
If all ok, HDPi support add later

**Comment by Foggalong** [comment]
Of the two playlist icons, I kinda prefer the first. Yeah, happy to wait for HiDPi before merging :)

**Comment by varlesh** [comment]
@Foggalong Please check

**Comment by Foggalong** [comment]
Isn't the `ltr` icon the wrong way around?

**Comment by varlesh** [comment]
You said earlier that you do not like symlink edit-clear-locationbar-ltr to dialog-close. I create new icon, variation edit-clear-symbolic.

**Comment by varlesh** [comment]
This ltr
ltr
This rtl
rtl

**Comment by Foggalong** [comment]
Yeah, the icon names are pretty much the wrong way around. As you can see in your original screenshot clementine uses the bottom one while you pushed the top. Unless I've misunderstood? But yeah that's the general design to go for :)

**Comment by varlesh** [comment]
I suggest symlink edit-clear-locationbar-ltr to dialog-close, this better variant.
You agree?

**Comment by Foggalong** [comment]
No, for reasons mentioned above :/

**Comment by palob** [comment]
I think in the ``clear-locationbar`` case it's right that the ``rtl`` icon is (apparantly) the wrong way around.
The icon is used in a wrong way by Clementine. It is supposed to be at the and of a text entry field pointing against the direction you write.

As far as I understand here ``rtl`` or ``ltr`` means the direction your language is written (e.g. ``ltr`` for English, ``rtl`` for Arab).

**Comment by palob** [comment]
@varlesh I've had a look at your branch. All icons are perfectly aligned to the grid so the PR is ready to be merged from this perspective.

I'm still a bit unsure about the ``rtl/ltr`` thing.
In accordance to my explanation above the arrow in ``edit-clear-location-bar-rtl`` is supposed to point to the right and vice versa (``rtl/ltr`` doesn't refer to the arrow direction).

This is how it looks in other themes:
+ Adwaita
edit-clear_adwaita

+ elementary
edit-clear_elementary

+ Breeze (``rtl`` **seems to be wrong here**)
edit-clear_breeze

As I understand it the icon is supposed to be at the end of the text entry field.
Clementine however uses it at the beginning.

@varlesh Is the icon Clementine uses really ``edit-clear-location-bar-rtl`` instead of ``edit-clear-location-bar-rtl``?

Anyway, in order not to look awry the icon should point to the right. Maybe it's okay to replicate the mistake, Clementine might be the only program using it.

**Comment by varlesh** [comment]
Realy use edit-clear-location-bar-ltr, please see source:
https://github.com/clementine-player/Clementine/blob/master/data/icons/22x22/edit-clear-locationbar-ltr.png
I don't know why developers clementine use ltr icon and located on the left.
I not seen this icon anywhere else...

**Pull request merged**
