### PR TITLE
More inkscape icons

### PR DESCRIPTION
**Pull request by wa4557**
More inkscape icons. Less controversial  I'd say

| Icon  | Name |
| ------------- | ------------- |
|  | `draw-cuboid`|
|  | `draw-ellipse`|
|  | `draw-polygon-star`|
|  |`draw-rectangle`|
|  |`tool-measure`|
|  |`tool-tweak`|

### CODE REVIEW

**Comment by Foggalong** [comment]
@wa4557 which symbol is tool tweak for? I can't seem to find it in my Inkscape

**Comment by wa4557** [comment]
You can find it here: http://wiki.inkscape.org/wiki/index.php/Themable_icons

It's the third icon in the left-hand side toolbar

**Comment by wa4557** [comment]
I'll fix that this weekend. I'm not sure about the draw-cuboid suggestion though. Maybe moving it half a pixel to the right / left also solves the problem?

**Comment by palob** [comment]
If it doesn't look obviously off-cenre, why not?

**Comment by wa4557** [comment]
Done

**Comment by wa4557** [comment]
Great, I have a few more inkscape icons waiting to be completed :)

**Pull request merged**
