### PR TITLE
Adds workspace indicator status icons fixes #296

### LINKED ISSUE #296: Workspace indicator
Hello, 
i would like to request some icons as a support of workspace indicator 
the icons from the workspace 1 to 36, you can make a python script to generate other files (i can do that) 
The icons are on this folder : /usr/share/icons/hicolor/16x16/status
the icon names are : indicator-workspaces-X  with X = 1, 2, ..., 36
the icon looks like that
selection_002

Thanks a lot!!!

### PR DESCRIPTION
**Pull request by wa4557**
#296

### CODE REVIEW

**Comment by Foggalong** [comment]
Again needs aligning to grid, definitely the monitors and as much of the numbers as is possible without making them look silly (characters are always a pain so don't worry to much about these)

**Comment by wa4557** [comment]
Ok aligned. Inkscape verbs are quite powerful!

**Comment by Foggalong** [comment]
Good work on 22/24, but 16 still needs doing. If you feel the outline needs to be more than 1px, then at least one of the two (probably outside here) edges needs aligning to grid.
screenshot_2015-05-02_14-10-52

**Comment by wa4557** [comment]
Yeah I made an error the last time I pushed I missdid 16 somehow. Should be ok now

**Comment by Foggalong** [comment]
I'm looking at it and I think you can probably just go full on alignment with a 1px border.
screenshot_2015-05-02_15-20-20
The change in clarity seems to be worth it 
screenshot_2015-05-02_15-20-29

**Comment by wa4557** [comment]
Fine but I will do that tomorrow, that's quite some work because it can't be automated :/

**Comment by Foggalong** [comment]
Ah, fair enough :) Great job though on these, nice idea having them on the monitor too

**Comment by wa4557** [comment]
Ah cleverly using sed it was less work than expected :)

**Comment by Foggalong** [comment]
Thanks for the great work on this one <3

**Pull request merged**
