### PR TITLE
Adds gtk-select-color

### PR DESCRIPTION
**Pull request by wa4557**
Another icon from #315

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Can you symlink  this too #224 ?

**Comment by wa4557** [comment]
Yeah good thinking; I might play around a little bit more with the icon though, on second glance it's probably not good enough yet...

**Comment by wa4557** [comment]
Alternative:
color

**Comment by Foggalong** [comment]
@wa4557 Two of your `gtk-print*.svg` icons have crept into this pull by mistake :)

**Comment by wa4557** [comment]
:) Deleted them

**Comment by bil-elmoussaoui** [comment]
can you smlink ``` folder_color_picker.svg``` too?

**Comment by wa4557** [comment]
Yeah I was thinking about this, but I was unsure where to put those icons. `apps` `actions`?

**Comment by bil-elmoussaoui** [comment]
The icon was in ``` scalable``` before, but after the last update the icon is now in  ```16x16/actions```

**Comment by wa4557** [comment]
`actions` it is then

**Pull request merged**
