### PR TITLE
TCPDUMP mimetype

### LINKED ISSUE #379: Mimetype: application/vnd.tcpdump.pcap
Name: **Network Packet Capture**
Mimetype: **application/vnd.tcpdump.pcap**
Possible extensions: **.cap** **.pcap**

Description: **Packet capture from network, produced by softwares like tcpdump**
image

### PR DESCRIPTION
**Pull request by hlechner**
imageimageimageimageimage

Fixes #379

### CODE REVIEW

**Comment by Foggalong** [comment]
This is looking a lot better, but use path-difference rather than overlapping circles to create the hole effect :)

**Comment by hlechner** [comment]
Nice, now i think i understood how to do it.

I've converted the whole symbol in only one path, or should I make it in 2 paths?

**Comment by Foggalong** [comment]
Using multiple paths is fine, it's just not a good idea if you're using paths to conceal parts of other paths like here

**Comment by hlechner** [comment]
Sanity check:
```
grep -R -wi "stroke:#" * | grep -v "@2" | grep mimetypes
grep -R -wi "ellipse" * | grep -v "@2" | grep mimetypes
```
**OK**, nothing found

**Pull request merged**
