### PR TITLE
Add icon show-hidden

### PR DESCRIPTION
**Pull request by Germar**
I recently added an icon `show-hidden` in OSS backup software `Back In Time` ([I'm the main Dev atm](https://github.com/bit-team/backintime)). This will show the hidden files (dot files) if triggered. There was nothing appropriate in default themes.

This is my new icon designed similar to `Humanity | list-add`:
show-hidden

As I personally use Numix icon theme I'd love to have a Numix icon for this, too. This pull request is about adding this icon:
show-hidden-numix

### CODE REVIEW

**Comment by Foggalong** [comment]
Hey, thanks for the pull request! The coloured version of the icon needs to go in all of the size (resized and aligned appropriately) folders and then monochrome 16px version in the /scalable folders for Light and Dark respectively.

**Comment by Germar** [comment]
Oh, sorry. Never made an icon before. I did like you said.

**Comment by Foggalong** [comment]
No problem :+1: just a quick something I've noticed, you seem to have put a copyright notice in each of the files. This can't be included since it'll conflict with the license of the project.

`<!-- Copyright (C) 2015 Germar Reitze -->`

**Comment by Germar** [comment]
Removed them. I also changed to GPLv3 in Metadata as the previous license CC BY-NC-SA was not compatible.
Happy Holidays!

**Comment by wa4557** [comment]
Shouldn't the icons in `/scalable` be named `show-hidden-symbolic.svg`?

**Comment by Germar** [comment]
@wa4557 you're right. All other files are named like this. So I renamed `show-hidden.svg` also to `show-hidden-symbolic.svg`

**Comment by wa4557** [comment]
@Germar please remove the icons from `96` `128` and `256` they are actually not needed, and only reserved for special kind of `action` icons

**Comment by wa4557** [comment]
Designwise I'm also not 100% sure. It is a bit simple for an `action` icon. They are usually more "material design" like

**Comment by Foggalong** [comment]
Possibly make the Circle part `#2d2d2d`?

**Comment by Germar** [comment]
@Foggalong with `Circle part` do you mean the iris for all coloured icons? Or do you want to change `Numix-Light/scalable/actions/show-hidden-symbolic.svg` from `#353535` to `#2d2d2d'

**Comment by wa4557** [comment]
I guess he means the iris. The `scalable` need to stay as is :)

**Comment by Germar** [comment]
show-hidden2d2d2d

I'd rather make the iris `#6c71c4` than `#2d2d2d`:
show-hidden6c71c4ff

What do you think?

**Comment by wa4557** [comment]
The blue would maybe work with a different outline color? The green is not great imo...

**Comment by Germar** [comment]
show-hidden4caf50ff      show-hidden268bd2ff

I like the one with blue outline...

**Comment by Foggalong** [comment]
Try the first green there with the `#2d2d2d` iris :)

**Comment by Germar** [comment]
show-hidden2d2d2d_2
I like that one, too!

**Comment by Foggalong** [comment]
Go for that (Y)

**Comment by Germar** [comment]
Done! Thanks for the help

**Comment by Foggalong** [comment]
Excellent! Thanks for the great contribution, and keep up the great work with BIT :)

**Pull request merged**
