### PR TITLE
subtitle mimetype restyled

### PR DESCRIPTION
**Pull request by hlechner**
- Changed color from ``#ffffff`` to ``#f9f9f9``
- Unified the two paths that composed the symbol
- Restyled the symbol to something not too squared

Actual:
imageimageimageimageimageimage

New:
imageimageimageimageimageimage

### CODE REVIEW

**Comment by Foggalong** [comment]
Prefer the old symbol, sorry!

**Comment by hlechner** [comment]
I thought it was too squared, ok then I can use the old one just adjusting the color and merging the paths

**Comment by palob** [comment]
What do you mean by adjusting the colour?
Pure white is correct for mimetype icons.

**Comment by hlechner** [comment]
If it's pure white is ok, maybe I can close this pull request then. :+1:

**Pull request closed without merging**
