### PR TITLE
Add foursquare icons

### PR DESCRIPTION
**Pull request by forivall**
follow-up to #978

### CODE REVIEW

**Comment by Foggalong** [comment]
Your horizontal and vertical lines need aligning to grid :)
screenshot_2016-01-18_19-48-58

**Comment by forivall** [comment]
Updated. During my first commit, I tried to snap the inside to the pixel grid, but didn't like how it looked. But I got it this time. :smile_cat:

**Comment by Foggalong** [comment]
@forivall All the others need the same treatment too :P

**Comment by forivall** [comment]
yup, wip right now

**Comment by forivall** [comment]
and done.

**Comment by Foggalong** [comment]
Still has some alignment problems. This horizontal line at size 48px...
screenshot_2016-01-19_09-58-07
...this vertical line at 64px...
screenshot_2016-01-19_10-02-51
...and this little artefact which seems to have crept into all sizes 32px and above. 
screenshot_2016-01-19_10-01-55

**Comment by forivall** [comment]
For the horizontal line issue, did you mean 22px? because that's where I fixed it. :smile:

**Comment by Foggalong** [comment]
16px is still not aligned here.
screenshot_2016-01-23_13-23-56
-----
Bottom node of the inner left vertical still isn't to grid in 32px.
screenshot_2016-01-23_13-28-05
-----
Bottom node of the inner left vertical still isn't to grid in 64px.
screenshot_2016-01-23_13-33-39

**Comment by forivall** [comment]
fixed up those last few alignment issues. Do you want me to squash this PR?

**Comment by Foggalong** [comment]
Nah, it's alright as is. I'll review latest changes tomorrow :+1:

**Pull request merged**
