### PR TITLE
Adds status icons for indicator-usb.svg

### LINKED ISSUE #295: Usb indicator icon
Hello, 
i would like to request an icon for the usb indicator icon 
the default icon (on hicolor folder)
selection_001
Elementary style 
selection_002
the icon folder : /usr/share/icons/hicolor/22x22/status
the icon name : indicator-usb

Thanks

### PR DESCRIPTION
**Pull request by wa4557**
Fixes #295

### CODE REVIEW

**Comment by Foggalong** [comment]
Needs aligning to grid too!

**Comment by wa4557** [comment]
I did my best :)

**Comment by Foggalong** [comment]
The square part on the left definitely needs aligning too, as well as the little bit of straight line below both the circle and the square :)

**Comment by wa4557** [comment]
Ok 22 and 24 are now perfectly aligned 16 is not possible without completely destroying the design

**Comment by Foggalong** [comment]
Excellent work! Yeah, 16px can be a pain to fit to. Imagine what it would be like if we supported Mints ludicrous 8px icons ;)

**Pull request merged**
