### PR TITLE
Changes design of gsm-3g* and adds scalable icons

### PR DESCRIPTION
**Pull request by wa4557**
Makes design of gsm-3g icons consistent with new wifi icons and adds the same icons as `network-cellular-signal-*` from #437 in `scalable`

### CODE REVIEW

**Comment by wa4557** [comment]
Btw: I think this icon would be also a better template for the `nm-tech-*` icons I recently added. @Foggalong what do you think? (The letters need to stay however)

**Comment by wa4557** [comment]
This is what I would envision the new icons should look like: 
unbenannt

**Comment by Foggalong** [comment]
Woah, that's looks really really neat. Love it :heart:

**Comment by wa4557** [comment]
Fine I'll change that in the next few days. I'll open another PR though, so this one can be merged :)

**Pull request merged**
