### PR TITLE
Added Colour Chart

### PR DESCRIPTION
**Pull request by dirtydancing**
Following-up on https://github.com/numixproject/numix-icon-theme/issues/286 and https://github.com/numixproject/numix-icon-theme/issues/282, this is a colour chart placed at the end of the Readme.

Screenshot:

colour-chart

### CODE REVIEW

**Comment by wa4557** [comment]
@dirtydancing I think this needs some changes, doesn't it :)?

**Comment by dirtydancing** [comment]
Yeah, will do :-)

**Comment by wa4557** [comment]
Btw: You're missing the blue color from the `indicator-messages-new.svg`

**Comment by dirtydancing** [comment]
Good occasion to include that as well then, thanks.

**Comment by Foggalong** [comment]
This is a nice idea, but shouldn't be on the main readme that the users see. With the redesign anyway all the colours should be the same for status icons :)

**Comment by dirtydancing** [comment]
Understood. This is indeed not pointing to the users. Actually, I asked a user for some feedback on this, and he thought this might be a sort of "reset button" (?) to get back to the defaut colours. No idea if that interpretation is representative, but this confirms that the main readme is not the place to put this on. Right now, I cannot think of another place to put this on, either. And with the redesign, there is consistency and more simplicity (no shadow) anyways.

So I am closing this.

**Pull request closed without merging**
