### PR TITLE
added cursor mimetypes

### PR DESCRIPTION
**Pull request by hlechner**
imageimageimageimageimageimage
imageimageimage
imageimageimage

**Mimetypes:**
- image/x-xcursor
- application/x-navi-animation #898 
- image/x-win-bitmap #898 

Further details: [here](https://github.com/hlechner/hl-numix-mime/issues/1)

### CODE REVIEW

**Comment by Foggalong** [comment]
The symbol should be `#f9f9f9ff` to fit with the guidelines :)

**Comment by hlechner** [comment]
Could be the color ``#f9f9f9`` but with some transparency?

The file with ``#f9f9f9ff``:
image

**Comment by hlechner** [comment]
Do you think that I should stay with the same background color?

here some tests of other background colors:
imageimageimageimageimage


and here the original background color with ``#f9f9f9ff`` plus 85% of opacity of cursor symbol:
image

**Comment by Foggalong** [comment]
No transparency, sorry. I'm alright with the colour as is :)

**Comment by hlechner** [comment]
Fixed.

btw, could you provide me the link to the numix base guideline? I want to take a look into it :thumbsup:

**Comment by Foggalong** [comment]
I'm not aware that we actually have written guidelines for the base theme, they're just sort of derived by looking at the patterns at all of the icons within a certain category.

I'm gonna have to do a major rewrite of the website fairly soon so I'll possibly add some more details guidelines then :)

**Comment by palob** [comment]
@hlechner On your 64px the vertical line of the **I**s look blurry. 
Try to move the **I** letters to the left/right or just the nodes effecting the position of the vertical line even if the resulting **I** will be slightly asymmetrical.

**Comment by hlechner** [comment]
image

I've made some changes, what you think @palob?

**Comment by palob** [comment]
That's crisp now :+1: 
But the lateral lines of the **I** now look a bit short in contrast to existing icons. Is it an illusion?

**Comment by hlechner** [comment]
image

The middle still with the same original size (2px), the top and bottom I need to remove less than 1px for each side L/R to avoid blurry there. should i change something?

**Comment by palob** [comment]
What results prolonging it by 0.5 (or 0.2, 0.7 ..) to each sides in?
Blurriness might not be that much of an issue in horizontal direction.

**Comment by hlechner** [comment]
1px:
image
0.7px:
image
0.5px:
image
0.2px:
image

which you think is the better?

**Comment by palob** [comment]
Hmm, 1,2 or 4. Not sure.
I'd say check an existing (not too blurry) 64px mimetype with an I at the end and choose what's comes closest.

**Comment by hlechner** [comment]
Some that I've checked are about 0.2, so I choose 0.2

**Comment by Foggalong** [comment]
The 16px icon needs bringing down half a pixel to counteract the triangle illusion. It's possible some of the other smaller sizes need this too, but not checked them has thoroughly

**Comment by palob** [comment]
Are the cursor symbols pure white?

**Comment by hlechner** [comment]
@palob no, I've used `#f9f9f9ff` instead as Foggalong's recommendation to follow the guideline.

**Comment by hlechner** [comment]
Sanity check:
```
grep -R -wi "stroke:#" * | grep -v "@2" | grep mimetypes
grep -R -wi "ellipse" * | grep -v "@2" | grep mimetypes
```
**OK**, nothing found

**Comment by Foggalong** [comment]
There are a few minor niggles with some of the symbols at specific sizes but I'm not sure how well they could be addressed without ruining the overall shape of the cursor. I'll merge now but we might come back to this some time down the line :)

**Pull request merged**
