### PR TITLE
Cleans up RSS icon

### LINKED ISSUE #1238: Issues with RSS related-icons
The symbolic icon (is it ``application-rss+xml-symbolic``?) looks like this in real life (screenshot from Vocal).
rssicon

Probably because of strokes rendering issues.
strokes

For some sizes the mimetype icon ``application-rss`` needs realignment.

All RSS icons should be redesigned in line with the symbol on the app icon.

### PR DESCRIPTION
**Pull request by wa4557**
Fixes #1238

### CODE REVIEW

**Comment by palob** [comment]
Thanks :+1:  how does it look with the symbol up 1px (maybe more for bigger sizes) for 24px onward?

**Comment by wa4557** [comment]
I think you meant 1px down? I think it's worse:

current:
  

1px down:
  

1px up:

**Comment by palob** [comment]
Yeah, down of course. I think it doesn't clash as much with the dog ear this way.

**Comment by wa4557** [comment]
Alright, going with one px down then

**Comment by palob** [comment]
I think all mimetype symbols are slightly off-centre.

**Comment by wa4557** [comment]
You're right, that might be a bit harder to fix...

**Comment by wa4557** [comment]
Only the 22px / 24px variant is off-centre. But to keep it aligned to grid we have to keep it that way...

**Comment by palob** [comment]
No, I was talking about the existing ones :) Most of the symbols are shifted down due to the dog ear.

**Pull request merged**
