### PR TITLE
inode/fifo mimetype icons

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
**inode/fifo mimetype**
_64px,48px,32px,24px,22px,16px icons:_

64px48px32px24px22px16px

*Edit: Issue https://github.com/numixproject/numix-icon-theme/issues/936*

### CODE REVIEW

**Comment by hlechner** [comment]
thanks @ChuckDaniels87 , good job!

**Comment by ChuckDaniels87** [comment]
You welcome @hlechner. It would be nice if anyone could check them. I'm not used to make numix base icons. :wink:

**Comment by palob** [comment]
16px isn't that easy to recognise and how does it look if the left side of the arrow is moved 1px to the right (arrow 1px narrower) for 48/32/22/24?

**Comment by ChuckDaniels87** [comment]
48px icon with 1px to the left:
48px

**Comment by palob** [comment]
Hmm I'm not that sure if it's better for 48px, how about 32/24...?

**Comment by ChuckDaniels87** [comment]
I made 16px symbol bigger and fixed arrows for all icon sizes:

16px 22px24px32px48px64px

**Comment by palob** [comment]
Hmm, sorry I think except for the 22/24 one it looked better before. 
The 16px one could use a simpler design.

**Comment by ChuckDaniels87** [comment]
Any suggestion for 16px icon?

*PS: Rolling back 32px,48px,64px*

**Comment by palob** [comment]
Honestly I'm not that sure what exactly this is about and what's a good metaphor :)

**Comment by ChuckDaniels87** [comment]
It is a thing called pipe, basically, first in - first out.

**Comment by palob** [comment]
OK, thanks. Maybe just get rid of the vertical lines for the 16px?

**Comment by hlechner** [comment]
Maybe a perfectly alignment?
image

The trouble with 16px is that every single node must be perfectly aligned, maybe is that.

@palob 
I think it's what chuck desire to design:
image

**Comment by ChuckDaniels87** [comment]
@hlechner yeah, pump-like symbol. Check out this one with both fixes ( @hlechner and @palob  ):

16px

**Comment by palob** [comment]
How does it look like when the line is going vertical (would save some horizontal estate)?

**Comment by ChuckDaniels87** [comment]
Sorry @palob, I don't understand what you mean.

**Comment by hlechner** [comment]
if I understood is it that palob mean:
image

to use the symbol on vertical

**Comment by palob** [comment]
Yep, that but aligned :)

**Comment by ChuckDaniels87** [comment]
I think prefer it horizontal, but I can test it with some icon sizes
anyways.

**Comment by hlechner** [comment]
I think i understand palob, because it uses too much of horizontal space, but I agree with you that on horizontal maybe looks like better. Looking at my partial screenshot it remind me a medal on vertical.

if some ideas comes to my mind I will expose here.

**Comment by hlechner** [comment]
@ChuckDaniels87 and maybe if reduce the sides of the circle like that:
imageimage

Then it's possible to reduce 1px from each size.

**Comment by ChuckDaniels87** [comment]
@hlechner It seems it comes blurrier that way. I'm still looking for a fix to this.

**Comment by Foggalong** [comment]
I'm not sure on this symbol as a metaphor :/ It seems like it has a lot of problems and not really enough going for it

**Comment by Foggalong** [comment]
Gonna close this - new brainstorm needed, sorry @ChuckDaniels87

**Comment by ChuckDaniels87** [comment]
I agree with you, this symbol is not good enough. Let's think in something better.

**Pull request closed without merging**
