### PR TITLE
Indicator light dark

### PR DESCRIPTION
**Pull request by dirtydancing**
Added indicator light and dark for touchpad and for variety, in Numix (icon files and symlinks) and in Numix-Light (symlinks to Numix). Fixes https://github.com/numixproject/numix-icon-theme/issues/444, cf. discussion over there for touchpad and also for variety.

### CODE REVIEW

**Comment by wa4557** [comment]
@dirtydancing: Ah ok my bad,  you changed that so that the regular files (e.g. variety-indicator and variety-indicator-light) are now both in Numix-base and both symlinks are in Numix-light. I figured it would make more sense to keep the light variant in Numix-base and the dark variant in Numix-light and make symlinks in each of the both cases.

**Comment by dirtydancing** [comment]
Ah that. Yeah, I figured it would be best to keep both icon files in Numix base, because Numix base already has to be able to serve both icons, depending on the selection of the user.

And usually, when icons are used both in Numix base and in Numix-Light, they are in Numix base and then symlinks are added in Numix-Light. So from my perspective, this is just keeping it consistent.

**Comment by dirtydancing** [comment]
Wait, so are you saying that these icons are not needed in Numix-Light, because Numix-Light inherits from Numix base?

**Comment by wa4557** [comment]
Actually yeah. But on the other hand they don't do any harm neither

**Comment by dirtydancing** [comment]
Because in these cases, the indicator icons are of the some colour in Numix base and in Numix-Light, so the symlinks should not be needed.

**Comment by dirtydancing** [comment]
Good point anyways. Agreed that the symlinks do no harm. Probably this would need some testing to see if they can safely be removed from Numix-Light. Please feel free to go ahead with this if you want to.

**Comment by dirtydancing** [comment]
Otherwise I will look into this. Because there should not be icons/symlinks in Numix/Numix-Light that are not needed. iirc one exception have been the red battery status icons that are the same in Numix base and in Numix-Light, but still symlinks in Numix-Light were needed. But that should be the exception.

Just let me know if you would like to go ahead with this.

**Comment by wa4557** [comment]
Go ahead :) I'm away from computer more or less from now the whole weekend. But yes those symlinks are definitely not needed

**Comment by dirtydancing** [comment]
OK, I will go ahead :)

**Comment by dirtydancing** [comment]
Alas, I ran into some difficulties when testing this with Variety, until I figured out that something is off with Variety itself: apparently, the light icon `variety-indicator.svg` is themeable, but the dark icon `variety-indicator-dark.svg` is not. The Numix icon looks similar to the original icon, so this is not totally straightforward to recognise. But both these icons exist and should be kept in Numix. And yes, the symlink in Numix-Light can be removed, as Numix-Light inherits from Numix base. I checked with the light icon, and it worked. So I will now submit a pull request for this :)

**Pull request merged**
