### PR TITLE
Moves several status icons to panel

### PR DESCRIPTION
**Pull request by wa4557**
I tested most of the programs that have icons in status, and apart from a few "toxic" icon names (vlc, gnome-mplayer, brasero, fluxgui, nitroshare etc...) those were the only programs that were still displaying a circular icon in the tray (apart from the bluetooth icons of course). With that I think #190 is more or less fixed \o/

### CODE REVIEW

**Comment by dirtydancing** [comment]
What about `deluge.svg` in status? Is this one of the toxic icons? If yes, why did you delete it rather than rename it?

**Comment by wa4557** [comment]
Ah sorry, didn't explain that. Yes deluge is a "toxic" icon. However the program deluge uses `deluge-panel` as tray icon. Therefore the icon `deluge` (which is an icon that is definitely not used by any other program) doesn't make any sense, more so if it is renamed anyways. I guess the renaming only makes sense for icons that are not symlinks to "nice" icons

**Comment by dirtydancing** [comment]
OK, so `deluge.svg` basically is an unused icon that somehow made its way into Numix base? In that case, indeed deleting makes more sense than renaming it (and so keeping it for manual individual re-renaming and possible other future purposes).

**Comment by wa4557** [comment]
Yes. I guess the point in renaming icons is, that we don't loose the icons if at some point they will be used again. Not the case for `deluge.svg`

**Comment by dirtydancing** [comment]
Are you sure that `y-ppa-indicator.svg` needs to be moved to `panel`? When checking with Xubuntu 15.04, the Y PPA panel icon is correctly picked up in the panel when (as currently) located in `status`.

**Comment by wa4557** [comment]
Yes: 
bildschirmfoto vom 2015-07-07 17 55 48

**Comment by dirtydancing** [comment]
Interesting. So it seems that the Y PPA Manager indicator icon is behaving differently in different *buntu distros, a thing we have not seen so far iirc. Agreed that it should be included.

**Comment by wa4557** [comment]
Nothing surprises me anymore, concerning this issue...

**Comment by dirtydancing** [comment]
Confirmed to be necessary and working for deluge, kazam and tomboy (zim is not showing up in the panel in Xubuntu 15.04).

**Comment by dirtydancing** [comment]
Actually, the zim tray icon is showing up once you activate the respective plugin. Also zim is confirmed :+1:

**Comment by wa4557** [comment]
@dirtydancing  Any more apps, that needs to be fixed? I think we basically covered them all

**Comment by wa4557** [comment]
I moved the insync status icons, according to [this] issue report (https://github.com/numixproject/numix-icon-theme-circle/issues/2253) (Can't test insync)

**Comment by wa4557** [comment]
I really think that's it :P

**Comment by Foggalong** [comment]
Is clipman one of the icons that needs renaming?

**Comment by dirtydancing** [comment]
I am afraid that `simplescreenrecorder.svg` is a toxic icon and cannot be moved as such to `panel`.

**Comment by wa4557** [comment]
Damnit, you're both right , argh. I'll changethat

**Comment by wa4557** [comment]
Fine. It really should be ok now.

**Comment by dirtydancing** [comment]
I am also getting into difficulties with `clipit-trayicon.svg`, as also this one seems to be displayed in the icon overview (?). Can someone reproduce that?

**Comment by wa4557** [comment]
Yeah. Because the app designers were super stupid and used `clipit-trayicon` as app icon. wtf

**Comment by dirtydancing** [comment]
This issue is getting more and more amazing all the time :)

**Comment by wa4557** [comment]
As it turns out, also the copy icons (although arguably status icons) need to be moved :(

**Comment by Foggalong** [comment]
Anything else to go in this issue?

**Comment by wa4557** [comment]
Nope, I think that's it (for now probably). Testen all the other apps with
status icons

Joshua Fogg <notifications@github.com> schrieb am Mi., 08.07.2015, 0:00:

**Comment by dirtydancing** [comment]
Agreed. The icons that I was able to check with Xubuntu 15.04 looked all good, and at the moment no further app/status icons concerned with this issue come to my mind (except for bluetooth, of course, cf. https://github.com/numixproject/numix-icon-theme/issues/190#issuecomment-119197792, but that would best be dealt with in a separate PR anyways).

**Comment by wa4557** [comment]
I don't dare to say it, but if this PR is merged and the bluetooth indicators are dealt with as well, I think we can close #190 :P

**Pull request merged**
