### PR TITLE
Mimetype symlinks for LyricsX files

### PR DESCRIPTION
**Pull request by creepertron95**
https://github.com/timxx/lyricsx

### CODE REVIEW

**Comment by palob** [comment]
Is the name of the mimetype really just ``x-lyricsx``? As per their repo yes.

**Comment by creepertron95** [comment]
https://github.com/timxx/lyricsx/blob/master/data/desktop/mimetypes/x-lyrics.xml

**Comment by Foggalong** [comment]
@creepertron95 @palob do either of you have capacity to make this change?

**Comment by palob** [comment]
That's a good metaphor. I can look into this.

**Comment by palob** [comment]
Added the mimetype icons.

**Pull request closed without merging**
