### PR TITLE
Adds telegram status icons

### PR DESCRIPTION
**Pull request by wa4557**
telegram status icons
@bil-elmoussaoui This is proably something for your hardcode tray fixer?

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
@wa4557 i will do this asap, but the official telegram app uses those icons : icomute_22_0.png for the normal panel icon and ico_22_{1-100} for the unreaded messages. If you can create a symlink just for those in Numix theme and i will create the others using Hardcode Tray in .TelegramDesktop/tdata/icons

**Comment by wa4557** [comment]
@bil-elmoussaoui Can't you symlink `telegram-panel.svg` to `icomute_22_0.png` and `telegram-attention-panel.svg to those other 100 icons? I'm a bit resilient to create 100 icons just for hardcoded icons

**Comment by bil-elmoussaoui** [comment]
@wa4557 You only have to create two symlinks the first one is telegram-panel.svg to icomute_22_0.svg and telegram-attention-panel to ico_22_1.svg the others are automatically created using the script, otherwise i will have to create a database of each icon theme

**Comment by wa4557** [comment]
Ah ok; seems resonable

**Comment by Ghokun** [comment]
I had started a little repo for this. However not all distributions have that icons in .TelegramDesktop/tdata/ticons 

see: https://github.com/Ghokun/telegram-numix-tray-icons/issues/2

**Comment by bil-elmoussaoui** [comment]
@Ghokun The telegram indicator is the worst thing in the software. it's not working properly in all the linux distributions :/ In the Hardcode-Tray fixer i used the .TelegramDesktop directory to copy the icons there but before i verify if the folder exists so it's won't create any useless symlinks. We can't do any thing else until it will be fixed from the Telegram desktop team!

**Comment by Ghokun** [comment]
Is there a script to do this ?

**Comment by bil-elmoussaoui** [comment]
@Ghokun you can use [Hardcode-Tray fixer](https://github.com/bil-elmoussaoui/Hardcode-Tray)

**Pull request merged**
