### PR TITLE
Adds preferences-desktop-accessibility

### PR DESCRIPTION
**Pull request by wa4557**
Starting with the low hanging fruits from #437 :)

### CODE REVIEW

**Comment by palob** [comment]
Isn't this an app icon? Used for a settings plug?

At least it's in Circle.

**Comment by wa4557** [comment]
A Lot of cazegories icons are in circle. All of the prefernces icons are in categories

**Comment by Foggalong** [comment]
Where does elementary actually show categories?

**Comment by wa4557** [comment]
Idk but since the Icon is called prefernces- I guess somewhere where prefernces are present

**Comment by Foggalong** [comment]
If it's in the preferences we aim to have them look like app icons. We tried letting them have a different style (inc. the same as categories) but it was ultimately a failure because too many apps use icons also shown in the settings as their app icons.


screenshot_2015-09-05_18-05-30

**Comment by wa4557** [comment]
Yes, but there are already app icons, which means that the circle is used no matter what. That's just if base is used without circle

**Comment by wa4557** [comment]
But I agree: If there are `preferences-` icons in those lists I will look beforehand If an icon in circle already exists, and if not I will add one in circle and base

**Comment by Foggalong** [comment]
Ah, I see! Good thinking :)

**Pull request merged**
