### PR TITLE
Adds missing icons in 16x16 and 24x24 4

### PR DESCRIPTION
**Pull request by wa4557**
#368; with this pull request, all the icons that are in 22x22/status should also be in 24x24/status and 16x16/status

A few more issues remain however: first. A few icons in 24x24/status are not scaled correctly from 22x22/status, and all the symlinks from Numix are missing in Numix-Light. @Foggalong if you want I can address these issues

### CODE REVIEW

**Comment by Foggalong** [comment]
There's a conflict preventing this one being merged in, but I have no idea what it is :/

**Comment by wa4557** [comment]
Dang, I created the pull requests in a different order, and I think its `nvidia.svg` that I changed later on once more, because I forgot to change the color in Numix-light. Should I rearange that?

**Comment by Foggalong** [comment]
Ahhh. Yeah, I think rearranging it will make it mergeable :)

**Comment by wa4557** [comment]
Me neither, I'll revert everything up to the point it works:)

**Comment by wa4557** [comment]
Ok I close this and make a new one

**Comment by Foggalong** [comment]
Rightyo :)

**Pull request closed without merging**
