### PR TITLE
some symlinks for virt-manager

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
For #124

### CODE REVIEW

**Comment by wa4557** [comment]
You will have to do this in all sizes, I suppose

**Comment by bil-elmoussaoui** [comment]
The application uses only those icons, so there's no need for bigger sizes

**Comment by Foggalong** [comment]
It's a good idea to do it in ever size to remain flexible in case of upstream change and to make sure it work on LDPI, MDPI, HDPI, and XHDPI screens.

**Comment by bil-elmoussaoui** [comment]
Done

**Comment by wa4557** [comment]
256?

**Pull request merged**
