### PR TITLE
Cleans all categories icons

### PR DESCRIPTION
**Pull request by wa4557**
While working on a few icons from #450 I discovered that the categories icons (amongst others) are somehow crooked (partly; e.g. wrong page sizes, absolutely not aligned to grid, wrongly centered etc...). 
Since I really like the `categories` icons I started to fix these issues (and will continue to do so if you think this is a good idea). I didn't change colours or design (apart from alignment / size fixes)

- [x] application-community.svg
- [x] applications-3D.svg
- [x] applications-accessories.svg
- [x] applications-arcade.svg
- [x] applications-astronomy.svg
- [x] applications-biology.svg
- [x] applications-boardgames.svg
- [x] applications-cardgames.svg
- [x] applications-chat.svg
- [x] applications-debugging.svg
- [x] applications-development.svg
- [x] applications-drawing.svg
- [x] applications-electronics.svg
- [x] applications-engineering.svg
- [x] applications-filesharing.svg
- [x] applications-fonts.svg
- [x] applications-games.svg
- [x] applications-geography.svg
- [x] applications-geology.svg
- [x] applications-graphics.svg
- [x] applications-haskell.svg
- [x] applications-ide.svg
- [x] applications-interfacedesign.svg
- [x] applications-internet.svg
- [x] applications-java.svg
- [x] applications-libraries.svg
- [x] applications-lisp.svg
- [x] applications-mail.svg
- [x] applications-mathematics.svg
- [x] applications-monodevelopment.svg
- [x] applications-multimedia.svg
- [x] applications-ocaml.svg
- [x] applications-office.svg
- [x] applications-other.svg
- [x] applications-painting.svg
- [x] applications-perl.svg
- [x] applications-photography.svg
- [x] applications-physics.svg
- [x] applications-profiling.svg
- [x] applications-publishing.svg
- [x] applications-puzzles.svg
- [x] applications-python.svg
- [x] applications-roleplaying.svg
- [x] applications-ruby.svg
- [x] applications-science.svg
- [x] applications-simulation.svg
- [x] applications-sports.svg
- [x] applications-system.svg
- [x] applications-utilities.svg
- [x] applications-versioncontrol.svg
- [x] applications-viewers.svg
- [x] documentation_help.svg
- [x] gnome-applications.svg
- [x] gnome-graphics.svg
- [x] gnome-settings.svg
- [x] gnome-system.svg
- [x] package_graphics.svg
- [x] package_system.svg
- [x] preferences-autocompletion.png
- [x] preferences-calendar-and-tasks.svg
- [x] preferences-certificates.svg
- [x] preferences-composer.png
- [x] preferences-desktop-peripherals-directory.svg
- [x] preferences-desktop-personal-directory.svg
- [x] preferences-mail-accounts.svg
- [x] preferences-other.svg
- [x] preferences-system-directory.svg
- [x] preferences-system-network-proxy.png
- [x] preferences-system-network.svg
- [x] preferences-system.svg
- [x] redhat-graphics.svg
- [x] redhat-preferences.svg
- [x] redhat-system_settings.svg
- [x] redhat-system_tools.svg
- [x] system-help.svg
- [x] system_section.svg
- [x] xfce-graphics.svg
- [x] xfce-system.svg

### CODE REVIEW

**Comment by Foggalong** [comment]
That's totally fine with me. The categories icons are my least favourite part of the theme which is why I rarely (if ever) touch them. Thanks for doing it :)

**Comment by wa4557** [comment]
Oh come on :) I agree they seem to be a little bit antique, but some of them are very well designed. 

Should I push all of the fixes to this branch (like I did now) and if I'm finished you merge the PR, or do you want to split it up in several PRs?

**Comment by Foggalong** [comment]
You're fine to stick all your categories modification, enhancements, etc in one merge here :)

My main peeve with them is that they're amongst the last things which still have the same design as original Numix so look a bit out of place with everything else. As you say though, some are well designed.

**Comment by wa4557** [comment]
Cool, I'll report back here as soon as I'm finished. Might be a few days it's quite some work, and a bit dull :)

**Comment by Foggalong** [comment]
No problem! :D

**Comment by wa4557** [comment]
Ok I'm finished here. I tried to monimize the changes in design, just aligned everything (where possible) to grid and fixed other small errors (like invisbile nodes) and inconsistencies

**Comment by Foggalong** [comment]
This is incredible. Thanks so much for the work you put into this :)

**Pull request merged**
