### PR TITLE
Adds mintupdate tray icons

### PR DESCRIPTION
**Pull request by wa4557**
First part of #1020. Not sure where the other icons are supposed to be

### CODE REVIEW

**Comment by palob** [comment]
If you are unsure where to put them (``status``,``actions``,...) that doesn't actually matter from my experience. The icons will show up correctly anyway.

**Comment by wa4557** [comment]
Yeah sure but I don't know which kind of icons they are supposed to be. Are they action or status icons? (There is a difference in designing them, right?)

**Comment by Foggalong** [comment]
Afaik these are status icons used by the update software in the Cinnamon tray.

**Comment by wa4557** [comment]
Yeah the ones in this PR, sure. But arguably not the other ones that are linked in #1020

**Pull request merged**
