### PR TITLE
Calendar icons

### PR DESCRIPTION
**Pull request by wa4557**
A few icons from #450

### CODE REVIEW

**Comment by Foggalong** [comment]
Check yo diff

**Comment by Foggalong** [comment]
That's a really cool way of doing it! Kudos

A small changed I'd like to request though: can you switch the `view-workeek.svg` so that the rectangle covers the first ~3/4 of the dots/days. The ISO standard is the week starts on a Monday and it's the system [all of Europe and most of Aisa](http://i.imgur.com/75o2nUe.png) follows. It better distinguishes it from `view-upcoming-days.svg` too.

**Comment by wa4557** [comment]
I changed that. Well I'm from Europe so this design suits me better anyway :)

**Comment by Foggalong** [comment]
\O/

**Pull request merged**
