### PR TITLE
fixes #904 (application/vnd.geogebra.file)

### LINKED ISSUE #904: Geogebra Mimetype
Name: application/vnd.geogebra.file
Use: Geogebra graph files
Icon: 
screenshot_2015-12-05_20-41-22

### PR DESCRIPTION
**Pull request by hlechner**
fixes #904 
Added mimetype: application/vnd.geogebra.file

### CODE REVIEW

**Comment by palob** [comment]
Sweet :+1:

**Comment by Foggalong** [comment]
The 22/24 symbols feel like they need to be shifted slightly to the right to counteract the triangle illusion

**Comment by hlechner** [comment]
one pixel is enough?
image

**Comment by palob** [comment]
I think that looks worse than before.

**Comment by hlechner** [comment]
I tried to put it less than 1 pixel to right, but it was so blurry.

**Comment by hlechner** [comment]
I checked that the whole symbol was 10.5 of width, so I change it to 10:
image

So it is better centered now, what do you think?

**Comment by Foggalong** [comment]
Yeah, 1px definitely too much

**Comment by Foggalong** [comment]
Same again. y u use stokes?

**Comment by hlechner** [comment]
I didn't know at that time about strokes, I took the geogebra svg icon and I modified it, however the strokes was on it, I'll fix them.

**Comment by palob** [comment]
Yeah, a few old Circle icons still use strokes.

**Comment by Foggalong** [comment]
These icons are still using strokes and invisible shapes all over the place :(

**Comment by hlechner** [comment]
Holy sh**, I probably was miles away. I don't know why I fixed only the small circles but not the rest...

but anyway, I think I found a way to discover if there is any stroke or shapes:
```
grep -R -wi "stroke:#" * | grep -v "@2" | grep mimetypes
grep -R -wi "ellipse" * | grep -v "@2" | grep mimetypes
```

if someone with experience knows a better way to do it, please let me know.

I'll later check in my other Pull Requests for this too.

**Pull request merged**
