### PR TITLE
Breakpoint action icons for Octave

### PR DESCRIPTION
**Pull request by palob**
All ``bp-*`` icons from #870, preview over there.

### CODE REVIEW

**Comment by Foggalong** [comment]
While I get what you were going for with the design in keeping it consistent with octave it doesn't quite work. Possibly try putting the symbols inside the circles? Or without the circles (not sure in what context they're used, I only ever use CLI octave)? Or another design entirely?

**Comment by palob** [comment]
You can apply breakpoints to your code in order to only execute a specific part of the file.
The icons are for jumping from one breakpoint to another or removing all of them.

I think symbols inside the circle will work, just the brush is a bit problematic.
A cross or something inside instead would be a double destructive methaphor though.

**Comment by wa4557** [comment]
I hink the red circle should stay, in MATLAB it is also a red circle...

**Comment by bil-elmoussaoui** [comment]
The same in Code::Blocks

**Comment by Foggalong** [comment]
Good with the red circles then, but yeah maybe try a different idea for the symbols inside them :)

**Comment by palob** [comment]
Next iteration:
bp-icons2

**Comment by Foggalong** [comment]
Much much better :+1:

**Comment by palob** [comment]
Revised designs pushed :+1:

**Pull request merged**
