### PR TITLE
RAW image mimetypes

### PR DESCRIPTION
**Pull request by hlechner**
imageimageimageimageimageimageimageimageimageimageimageimageimageimage

imageimageimageimageimageimageimageimageimageimageimageimageimageimage

imageimageimageimageimageimageimageimageimageimageimageimageimageimage
imageimageimage

RAW Images mimetypes

Fixes hlechner/hl-numix-mime#7

Further details: [here](https://github.com/hlechner/hl-numix-mime/issues/7)

### CODE REVIEW

**Comment by palob** [comment]
I was about to do this one however my idea was to just use **RAW** on all of them, except for DNG and EXR

**Comment by hlechner** [comment]
I didn't know about this EXR format before.

Yea, its not raw format but I can create a EXR mimetype with text for this one, should I add in this pull request or in a new one?

**Comment by palob** [comment]
Thanks, better a new one. It's ``image-x-exr`` by the way.

**Comment by Foggalong** [comment]
Is there any way we could get this more aligned to grid? It's very blurry as is.

**Comment by hlechner** [comment]
I'll do my best on these icons.

I thought wasn't that bad. which sizes do you think is acceptable or maybe all sizes is so blurry?

**Comment by Foggalong** [comment]
It's not terrible, but the smaller sizes especially could do with better alignment

**Comment by hlechner** [comment]
image -> image

better or worst?

**Comment by palob** [comment]
The lower one I think is an improvement :+1:

**Comment by ChuckDaniels87** [comment]
I agree with @palob. :+1:

**Comment by Foggalong** [comment]
Yeah :+1:

**Comment by hlechner** [comment]
imageimageimage

**Comment by palob** [comment]
What's the with of the symbol on the 16px one? Can you get it any larger without looking goofy?

**Comment by hlechner** [comment]
The symbol's size is 6x6 let me try 7x7 then

**Comment by palob** [comment]
Better use an even width/height. Otherwise you'll end up with a .5 X-position when centering.

**Comment by hlechner** [comment]
8x8 on 16px:
image
* It's the same icon size of symbol on 24px icon

**Comment by palob** [comment]
How looks the symbol from 22/24px on the 16px icon?

**Comment by hlechner** [comment]
The symbol from 24px (8x8) on 16px:
image

It's better then 6x6 or it's too large?

**Comment by palob** [comment]
It's easier to recognise as aperture at least. I think the size is tolerable.

**Comment by hlechner** [comment]
And how about up 8x8 to 10x10 into the 22/24?

Here the test:
image

**Comment by palob** [comment]
:+1:

**Comment by hlechner** [comment]
32:
imageimageimageimageimageimageimageimageimageimageimageimageimageimage
22/24:
imageimage
16:
image

I've also repaired the 32px text, some letters were a bit blurry

**Comment by hlechner** [comment]
Guys, what do you think now? and how about the 48 and 64?

**Comment by palob** [comment]
I think it's all fine now. 
If you've got some extra time: I wonder if 16px could be slightly crisper (don' know if that's possible), 64px symbol looks like it could be a bit (2px to 4px) bigger.

**Comment by hlechner** [comment]
actual:
image
tests:
imageimageimageimage

It's hard in this size.

**Comment by hlechner** [comment]
64px:
image

The symbol above is 4px larger then the previously. I think it's better, should I change the icons to this size?

**Comment by palob** [comment]
The new 64px is great.

The leftmost 16px test might be a tiny bit better than before but I'm not sure. Let' see what others think.

**Comment by wa4557** [comment]
Yeah the leftmost is better imo

**Comment by dirtydancing** [comment]
Wow, great work!

As to the 16px size: to me, the actual one looks better than the proposed leftmost one. The actual one to me is not really more blurry, and the actual one`s "thickness" is more consistent with the larger sizes. The proposed leftmost one is just fine as well, though :)

**Comment by hlechner** [comment]
Sanity check:
```
grep -R -wi "stroke:#" * | grep -v "@2" | grep mimetypes
grep -R -wi "ellipse" * | grep -v "@2" | grep mimetypes
```
**OK**, nothing found

**Comment by palob** [comment]
@hlechner There is the ``image-x-hdr`` mimetype for HDR images (*Radiance format*).

While it's not RAW I think your new mimetpe is fitting.

**Comment by hlechner** [comment]
I agree with you @palob, the mimetype is not the most appropriated because it's not the RAW file, however the HDR is closer to RAW then a normal image at my perception.

I'll do it and then I send a new PR.

**Comment by wa4557** [comment]
@hlechner can you wait with sending a new PR until the maintenance PRs have been merged? Otherwise there will be conflicts. Adding something new is good to go, but changing something will lead to conflicts...

**Comment by hlechner** [comment]
@wa4557 ok, no problem

**Comment by palob** [comment]
@hlechner Did you already work on the HDR mimetypes? Otherwise I can do it.

**Comment by hlechner** [comment]
I'm involved in other project right now,  so i didn't finish it.

please go ahead if you can, thanks.

**Comment by palob** [comment]
Alright :+1:

**Pull request merged**
