### PR TITLE
Adds library-places

### PR DESCRIPTION
**Pull request by wa4557**
from #437

### CODE REVIEW

**Comment by palob** [comment]
That's a rad one :+1:

**Comment by Foggalong** [comment]
Same with this icon - do we know where this icon is used?

**Comment by wa4557** [comment]
No plan. I just thought that since it is not a folder icon something similar to the non folder icons in places might be the right choice

**Comment by Foggalong** [comment]
That's my worry - if it's something representing a directory in the file system it needs to be a folder to stay consistent with the others. Anyone who uses elementary know where this shows up?

**Comment by bil-elmoussaoui** [comment]
@Foggalong Those are the default icons from elementary-icon-theme
screenshot from 2016-06-20 00-47-24

**Comment by Foggalong** [comment]
@bil-elmoussaoui Any idea where they're used though?

**Comment by bil-elmoussaoui** [comment]
@Foggalong Never seen those icons anywhere. But there still in the latest version of elementary-icon-theme (launchpad); they only exists on 16px; i think they're from luna..

**Comment by palob** [comment]
If they're only made for 16px I think it's quite probable they won't appear in place of folders.

**Comment by Foggalong** [comment]
Probably safe to merge these two issues then and just see if they crop up somewhere they shouldn't :)

**Pull request merged**
