### PR TITLE
Exr

### PR DESCRIPTION
**Pull request by hlechner**
imageimageimage

``image-x-exr``

### CODE REVIEW

**Comment by palob** [comment]
Thanks!
I think the preferred way to this is to have symlinks to the default image mimetype for 16/22/24px as well even if is likely to default to that one anyway.

The letters on the 32px one look a bit slim. Is it bold font weight?

**Comment by hlechner** [comment]
image

First I though it was just my impression, but it wasn't I probably miss clicked the bold or the apply button before. Also created the links.

**Comment by wa4557** [comment]
One thing: You should convert the fonts to paths, because on some distributions the Ubuntu font might not be installed which results in errors...

**Comment by hlechner** [comment]
I did it, and also repair manually each letter for a better appearance.

**Comment by wa4557** [comment]
Oh sorry, I was just looking at the source code and there are still some remnants from the font left :)

**Comment by hlechner** [comment]
Thanks I see now, it's strange because when I open with inkscape it shows as path.

the method that i used was: select the font and go to "Object to Path"

**Comment by palob** [comment]
Hmm, that should do the trick actually.

**Comment by hlechner** [comment]
new tests: I've manually edited the code and remove the part of ubuntu mention and it look exactly as before.

I selected the whole filename actually

**Comment by hlechner** [comment]
on that lines if you replace by this:
```
style="fill:#ffffff;"
```

it will work as the same, just need the color otherwise will be black.

I think inkscape do not remove some kind of information from file even if it will not be used it anymore.

**Pull request merged**
