### PR TITLE
New design for nm-tech*

### PR DESCRIPTION
**Pull request by wa4557**
As proposed a new design for `nm-tech-*` in #934. Also fixed a incorrect icon from a previous PR

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
@wa4557 Maybe adding 4g icon too? can be symlinked to the ones in #826

**Comment by Foggalong** [comment]
Which ones?

**Comment by bil-elmoussaoui** [comment]
sorry i meant #827 , the `network-cellular-*` ones

**Comment by wa4557** [comment]
What letters should be there? 4G or LTE?

**Comment by bil-elmoussaoui** [comment]
This is the list of icons in #827 
- network-cellular-3g
- network-cellular-4g
- network-cellular-acquiring
- network-cellular-connected
- network-cellular-edge
- network-cellular-gprs
- network-cellular-hspa
- network-cellular-no-route
- network-cellular-offline

I will vote for 4G ;)

**Comment by Foggalong** [comment]
Well 3g should clearly be 3g :P

**Comment by wa4557** [comment]
I've add 4g files and symlinks for the icons fro #827

**Pull request merged**
