### PR TITLE
Rearranged bluetooth-* and blueman-* icons

### PR DESCRIPTION
**Pull request by dirtydancing**
Proceeded as laid out in https://github.com/numixproject/numix-icon-theme/issues/190#issuecomment-119197792 and following.

Addresses https://github.com/numixproject/numix-icon-theme/issues/190
Addresses https://github.com/numixproject/numix-icon-theme/issues/192
Fixes https://github.com/numixproject/numix-icon-theme/issues/438

### CODE REVIEW

**Comment by wa4557** [comment]
Just as a proof that this works as expected (and already did for years in the ppa)

**Comment by Foggalong** [comment]
DO NOT DELETE YOUR REPO YET. If I need to revert this pull it's a lot easier if your repo is still in place

**Comment by dirtydancing** [comment]
@foggalong Is it safe to delete the branch now?

**Comment by Foggalong** [comment]
@dirtydancing I believe so :)

**Pull request merged**
