### PR TITLE
Renamed several status icons

### PR DESCRIPTION
**Pull request by dirtydancing**
Addresses https://github.com/numixproject/numix-icon-theme/issues/192. Cf. conversation over there.

### CODE REVIEW

**Comment by wa4557** [comment]
Hmm by doing this renaming you have now a few broken symlinks. `spotify-indicator.svg` for example points to `spotify-client` which isn't there anymore. You should adapt those symlinks

**Comment by dirtydancing** [comment]
Thanks, Yeah :) Just corrected Google-Chrome. Will check spotify next.

**Comment by pgera** [comment]
Can this be merged ? Hoping this fixes the monochrome icons.

**Comment by Foggalong** [comment]
There's a lot more than this one that needs to be done before the fix for that lands, bit its hopefully the first step yes :)

**Comment by dirtydancing** [comment]
Well, this depends on what @pgera is referring to with "monochrome icons". This pull request will indeed (for some usual suspect icons) fix the "toxic" monochrome icons showing in GNOME Shell as app icons :)

At the same time, this is all part and one of the steps of the showdown for the infamous https://github.com/numixproject/numix-icon-theme/issues/190, which is concerned rather with the "monochrome icons" (status icons) in the panel of Ubuntu & Co.

And as commented e.g. over at https://github.com/numixproject/numix-icon-theme/issues/190#issuecomment-117362367, the fixes for both of these issues, https://github.com/numixproject/numix-icon-theme/issues/192 and https://github.com/numixproject/numix-icon-theme/issues/190, can flexibly be done in parallel, it is not necessary to do one before the other.

**Comment by pgera** [comment]
I was referring to the former. i.e. Chrome, vlc etc. showing up monochrome in unity panel/dash.

**Comment by dirtydancing** [comment]
Thanks for clarifying @pgera, all of this is a somewhat complex set of issues, to say the least. At least, we can now clarify that indeed this pull request will (start to) fix the issue that you were referring to :)

**Comment by wa4557** [comment]
@dirtydancing I'm sorry but I think you have to do that again, as well. My last PR destroyed this one :(

**Comment by dirtydancing** [comment]
@wa4557 no problem :) Please just include these icons in your new PR, it is probably even better when every icon has a specific commit, just as for https://github.com/numixproject/numix-icon-theme/issues/190. Thanks!

I will just close this PR then.

**Pull request closed without merging**
