### PR TITLE
Type=Fixed for 16,22,24,32px icons

### LINKED ISSUE #948: Blurry 24px action icons in Qt/GTK2 filechoosers and Octave, VLC
blurry1
blurry2
blurry3

The issue is due to 16px 22px or 32px (don't know exactly) action icons showing up in place of 24px ones.

This issue isn't present with other themes like Adwaita, breeze or elementary.

Adwaita and breeze have set ``Type=Fixed`` for actions icons in all sizes.
elementary has set ``Type=Scalabe`` like Numix (and the same Min/Max sizes except for 24px) but they haven't got 22px action icons.

Setting ``Type=Fixed`` in the Numix ``index.theme`` for 16,22,24,32 actions and the respective @x2 ones (haven't pinpointed it any more specifically) fixes the issue.

What do we need ``Type=Scalable`` for anyway?
Are they any non-hardcoded action icons with other sizes than 16,22,24,32....?
Those would show up blurry anyway.

### PR DESCRIPTION
**Pull request by palob**
Changed the icon type to ``Fixed`` for all sub-48px icons except for ``16/emblems``.
Making the action icons fixed size fixes #948.

### CODE REVIEW

**Comment by wa4557** [comment]
You could actually make all the larger places folders also fixed (except 256 maybe for bigger sizes) . But it doesn't matter actually

**Comment by wa4557** [comment]
@palob Can you also add folders `scalable/emotes` in this PR. Otherwise I will have to open another PR that is conflicting with this one (I recently added two icons there...)

**Comment by palob** [comment]
@wa4557 Which icons are you referring to?
Should I add
```
[scalable/emotes]
Size=16
MinSize=16
MaxSize=512
Context=Emotes
Type=Scalable
```
to the ``index.theme`` or do the folder ``scalable/emotes`` as symlink to a fixed-size emotes folder?

**Comment by wa4557** [comment]
First one. I'm talking about this folder https://github.com/numixproject/numix-icon-theme/tree/master/Numix/scalable/emotes

**Comment by palob** [comment]
Ahh yes, looks like I haven't pulled the latest git changes.

**Comment by palob** [comment]
Done :+1:

**Comment by wa4557** [comment]
Thx

**Comment by wa4557** [comment]
@palob In case you haven't seen my last edit in the previous post, you have to add the same folder in Numix-Light as well :)

**Comment by palob** [comment]
Aye :)

**Comment by hlechner** [comment]
And how about the 8px icons that were created as 16px? in this case the fixed type couldn't be problematic?

I didn't tried it because I don't remember which icons actually were 8px.

**Comment by palob** [comment]
Do you know of any place where 8px icons are used?

**Comment by wa4557** [comment]
I think we shouldn't really care about the stupidity of having `8px` icons. It's relatively useless since screen resolutions become larger and larger... `16px` is really the smallest I have ever seen on my computer.

That being said, keeping the `scalable` part for the `16px` icons might induce exactly those errors why we removed them in the first place...

**Comment by Foggalong** [comment]
Cinnamon use[s,d] 8px icons in some parts of the interface, but other than that they're basically nowhere. It doesn't really make sense to cover them in Numix - it's a lot of work for a vanishing use case

**Comment by hlechner** [comment]
got it, make sense, too much work for a little result

**Comment by Foggalong** [comment]
Now, regarding the pull request - didn't we have a big thing just a few weeks ago where we switched everything to scalable?

**Comment by wa4557** [comment]
Yeah, but this is actually only necessary for sizes `48` and `64` because they are used for `96,128, 256 ...` the scalable part for the smaller sizes seem to introduce problems with Qt applications.... Numix is a complete theme so the scalable part is not really needed

**Comment by Foggalong** [comment]
And does having scalable at 48 and 64 not cause those problems also?

**Comment by wa4557** [comment]
The problem is that icons from larger sizes are used for smaller icons. So no, because there are no bigger sizes

**Comment by Foggalong** [comment]
The larger sizes do technically exist through their creation in `index.theme` even though the files don't physically exist

**Comment by wa4557** [comment]
Yeah that's however true. I'm not sure if there are additional problems; never thought much about the Qt way of selecting icons...

**Comment by Foggalong** [comment]
What would be the consequences of going back to everything (except `/scalable` ofc) as `Type=Fixed`?

**Comment by wa4557** [comment]
We would have to add the larger sizes again...

**Comment by wa4557** [comment]
Never programmed Qt before but I think I have a somehow similar program that simulates the Qt way of selecting icons. For me it seems that only the smaller icons are blurry....

Code (@Foggalong you might add that to numix-labs as well?)
```
from PyQt5 import *
from PyQt5.Qt import *
from PyQt5.QtWidgets import *
import sys

class MyMainWindow(QMainWindow):

    def __init__(self, parent=None):

        super(MyMainWindow, self).__init__(parent)
        self.form_widget = FormWidget(self) 
        self.setCentralWidget(self.form_widget) 

class FormWidget(QWidget):

    def __init__(self, parent):        
        super(FormWidget, self).__init__(parent)
        self.layout = QHBoxLayout(self)

        sizes=[16,22,24,32,48,64,96,128,256]
        icon = QIcon.fromTheme('distribute-horizontal-right')
        for i, size in enumerate(sizes):
            label = QLabel()
            label.setPixmap(icon.pixmap(size))
            self.layout.addWidget(label)
        self.setLayout(self.layout)

app = QApplication([])
foo = MyMainWindow()
foo.show()
sys.exit(app.exec_())
```

and screenshot:
bildschirmfoto 2016-01-07 15 35 01

**Comment by wa4557** [comment]
With @palob s branch
unbenannt

**Comment by wa4557** [comment]
It is a bit hard to see the difference in the screenshots above, but if you run the code it is clearly visible...

**Comment by wa4557** [comment]
Ah ok, looking at the screenshots indeed the bigger sizes also need the "Fixed" entry. Damn...

**Comment by wa4557** [comment]
This improved code confirms what I was fearing: Qt doesn't seem to understand the `scalable` part in the index.theme

```
from PyQt5 import *
from PyQt5.Qt import *
from PyQt5.QtWidgets import *
import sys

class MyMainWindow(QMainWindow):

    def __init__(self, parent=None):

        super(MyMainWindow, self).__init__(parent)
        self.form_widget = FormWidget(self) 
        self.setCentralWidget(self.form_widget) 

class FormWidget(QWidget):
    def __init__(self, parent):        
        super(FormWidget, self).__init__(parent)
        self.layout = QHBoxLayout(self)
        sizes=[16,22,24,32,48,64,96,128,256]
        icon = QIcon.fromTheme('distribute-horizontal-right')
        print(icon.availableSizes())
        for i, size in enumerate(sizes):
            label = QLabel()
            label.setPixmap(icon.pixmap(size))
            self.layout.addWidget(label)
        self.setLayout(self.layout)

app = QApplication([])
foo = MyMainWindow()
foo.show()
sys.exit(app.exec_())
```

**Comment by Foggalong** [comment]
@wa4557 Added the [second version](https://github.com/numixproject/numix-labs/blob/master/Andreas/qt-test.py)

**Comment by wa4557** [comment]
Ok in conclusion to this, I think we can say, that @palobs branch is fine at least when looking at the above screenshots...

**Comment by wa4557** [comment]
Ok forget this, there are several problems with the Qt lookup mechanism:

Current situation:
GTK/Qt
bildschirmfoto 2016-01-07 18 40 00

@palob branch
bildschirmfoto vom 2016-01-07 18-43-32

**Comment by Foggalong** [comment]
oh damn, that's not good

**Comment by wa4557** [comment]
No it isn't... One thing we can do: Change everything back to `Fixed`. 
Create folders `96` and `128` (and `96@2x` etc. oc) and symlink `48` to `96` (the actual size doesn't matter) and everything from `64` to `128`. 
In the `index.theme` we can make everything fixed except all the `128` folder which we use for all the bigger sizes...

**Comment by palob** [comment]
@wa4557 Great example code!

So you mean renaming ``48`` to ``96``?

**Comment by wa4557** [comment]
@palob You need both folders `48` and `96` but in the `96` folder it is ok to have icons which are `48px`. So symlinking from `48` to `96` (same for `64` and `128`) should be fine

**Comment by palob** [comment]
Do we actually need the dedicated SVG designs in ``96``, ``128`` and ``256`` or is this just scaled up from ``64``?

**Comment by wa4557** [comment]
The problem is, that we need a dedicated `96` folder because it cannot be scaled from `64px`

**Comment by palob** [comment]
Are they distinct from the ``48`` ones?

**Comment by wa4557** [comment]
No. Which means they can be symlinked

**Comment by palob** [comment]
So all icons, including ``@x2`` will scale correctly regardless of ``Fixed?
And it doesn't break the GTK situation?

**Comment by wa4557** [comment]
Oh yeah,didn't think about it is all fixed now. I'm afraid we have to add the bigger sizes then :(

**Comment by palob** [comment]
What I wondered before, do non ``apps``/``places``/``mimetype icons really exist in above-``64px`` sizes, i.e is there app using such?

**Comment by wa4557** [comment]
Nevermind my idea works :) All fixed (except `128` which still has the `scalable` part. Seems to be all good 
bildschirmfoto vom 2016-01-07 21-28-14

**Comment by palob** [comment]
How about the HiDPI ones? ``Fixed or ``Scalable``?

**Comment by wa4557** [comment]
Fixed. But the `Scale=2` has to stay...

**Comment by palob** [comment]
And we better hadn't toss the ``96`` and ``128`` SVGs?

If you set ``scalable/apps`` to ``Fixed`` in the Numix Circle index the app icons (>48px) show up blurry in the Shell overview.

So will there be all fine with >64px mimetype icons?

**Comment by wa4557** [comment]
Yeah because if you set `scalable/apps` to `Fixed` with `Size=16` the system is only showing `16px` icons. But if you have `48px` icons in the `96` folder and set `Size=96` `96px` icons are shown. 

I wouldn't toss sizes > 64px. Screens become bigger and bigger these days...

**Comment by palob** [comment]
I meant tossing the non-symlink SVGs.

**Comment by wa4557** [comment]
No I don't think we can toss them. The `places` icons are very distinct...

**Comment by palob** [comment]
Alright, I'll add the symlinks and the respective sections to the index file and set everything to ``Fixed`` save for ``128`` and ``128@x2``.
``Scalable`` too for the ``256`` stuff?

**Comment by wa4557** [comment]
Yeah all the `256` scalable. All the `128` also `scalable` except for `places` which needs to be fixed.

**Comment by wa4557** [comment]
You can symlink whole folders from `48` to `96` (same for `64`) except for `actions` I guess. We have to symlink all icons there individually...

**Comment by palob** [comment]
Why is that?

**Comment by wa4557** [comment]
Because there exist already `action` folders in `96` and `128` so we can't symlink the whole folder... But a     `find . -iname "*.svg" -exec ln -s {} ../../96/actions \; ` should do the trick

**Comment by palob** [comment]
I would have symlinked the whole folder and pasted the existing back in.

**Comment by wa4557** [comment]
That wouldn't work, because then you would replace the icons in the source folder...

**Comment by palob** [comment]
Well, ``find`` outputs the filenames with ``./`` at the beginning. Since I couldn't ``sed`` or ``cut`` that away in combination with ``find -exec`` I've ended up with this:
``SVGS=($(ls)); for i in ${SVGS[@]}; do ln -s ../../64/actions/$i ../../128/actions/$i; done``

**Comment by wa4557** [comment]
Sorry for the confusion, but you can actually ditch the `128` symlinks if you make `96` Fixed and keep `64` as scalable. So only symlinks from `48`to `96`necessary

**Comment by wa4557** [comment]
Ok I had a closer look at `places` (and the `places` related `action` icons) in `96` `128` and `256`; and the good news is they are NOT distinct. They are in fact only scaled up versions of the icons in `48` and `64`. This means that they can be removed, and the same procedure as for the other folders can be used. So my proposal is now

1. Remove folders `places` and `actions` from `128`, `96` and `256` (also in `numix-folders`, saves a lot of overhead)
1. Symlink all folders in `48` (except `notifications`) to a newly created folder `96`
2. Change everything to `fixed` in the `index.theme` except all the `64` folders (with `Minsize=8` and `maxsize=512`)
3. Symlink all folders to their respective `@2x` folders for HIDPI support (also with the same `Fixed` `scalable` procedure)

This should then work with both GTK and QT and also removes a lot of overhead from `folders` and makes it easier to add new styles there. 
@Foggalong @palob What do you guys think?

**Comment by wa4557** [comment]
I've made a test repo to show how I envisioned the whole thing (a few modifications to my above list were necessary, QT really has problems when it comes to `Type=Scalable` but now it should work :)
https://github.com/wa4557/numix-icon-theme/tree/qt-test

Proof that it works:
unbenannt

**Comment by palob** [comment]
@wa4557  Alright, if it works out smoothly go ahead. I'll close this PR.
I can do a last real-life test with Octave 4 for your branch later.

**Comment by wa4557** [comment]
:+1: I've opened a PR: #990. I guess this one can be closed now. @palob What I wonder is if the `fileopen` icon in Octave now works

**Comment by palob** [comment]
I'll take it a ride tomorrow.

**Pull request closed without merging**
