### PR TITLE
New icons for guitar tabs files

### PR DESCRIPTION
**Pull request by althonos**
Hi ! 

Numix circle has nice icons for several guitar tabs editors (Tuxguitar, Guitar Rig, Guitar Pro) but none for the different file formats. Using the Tuxguitar pick symbol and base color, I made icons for the following tab files formats:

- `audio/x-tuxguitar` (Tuxguitar)
- `audio/x-gtp` (GuitarPro)
- `audio/x-ptb` (Power Tabs)

### CODE REVIEW

**Comment by althonos** [comment]
@palob : no problem, I was almost entirely sure I would not get everything right on the first try ! I hopefully fixed everything, properly offsetting elements on the different icons, and added the lower resolutions as well

**Comment by althonos** [comment]
> The pick symbol on the 16px icon should be deformed to a width of 6px and moved to X=6

I think you meant X=5 otherwise the pick itself is not centered anymore ! :wink:

Colors should be fixed, I couldn't grep any `#f9f9f9` anywhere after that commit.

**Comment by althonos** [comment]
Any update about this ? :smile:

**Comment by palob** [comment]
Wainting for the maintainer @Foggalong to chime in, nothing wrong on your side.

**Pull request merged**
