### PR TITLE
symlink edit-clear-rtl-symbolic to edit-clear-symbolic

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
See the comment of @palob in #273 
the already existing icon ```edit-clear-ltr-symbolic.svg``` is a ```rtl``` icon. I renamed the icon and symlinked the ```edit-clear-ltr-symbolic.svg``` to ```edit-clear-symbolic``` 
capture du 2015-07-03 19 09 03

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
@Foggalong can you take a look at this? just need to remove my fork ppa so i can push other symlinks/icons

**Comment by Foggalong** [comment]
I'm not merging any base stuff until we've finished dealing with #190 - if something comes up it makes reverting it  a lot easier.

**Comment by Foggalong** [comment]
@bil-elmoussaoui the current system is the one used by Adwaita so is presumably right. We haven't had any issue reports about this either

**Comment by bil-elmoussaoui** [comment]
I have checked this on elementary default theme, and you're right! i will close this then :+1:

**Pull request closed without merging**
