### PR TITLE
Renames several bad status icons

### PR DESCRIPTION
**Pull request by wa4557**
I was able to save most of my work (only a few conflicts \o/, git is really powerfull). I also added vlc, brasero and google-chrome, because @dirtydancing asked me to include them. 
I also ran `inkscape --vacuum-defs` again for those icons, because they were made before the last PR

### CODE REVIEW

**Comment by dirtydancing** [comment]
Just putting in a reference to https://github.com/numixproject/numix-icon-theme/issues/192, so it is clear which issue this PR addresses, and tracked in https://github.com/numixproject/numix-icon-theme/issues/192 :)

**Comment by Foggalong** [comment]
Just noticed there's the Chrome icons here. Would it make sense to instead move them to the icon names given in #613 so that they can be used?

**Comment by wa4557** [comment]
Partly, (there are the notification icons as well, I guess they need to be coloured blue). I'd still keep these icons and make symlinks to those. If a user wants to revert this whole `renamed-` thing the icons are already present...

**Comment by Foggalong** [comment]
I guess that makes sense, though we will eventually have to draw the line somewhere (when developers update their app to fix the problem for example).

**Comment by wa4557** [comment]
Yeah true. I'll add the chrome icons when and if this PR is merged :)

**Comment by Foggalong** [comment]
DO NOT DELETE YOUR REPO YET. If I need to revert this pull it's a lot easier if your repo is still in place

**Comment by wa4557** [comment]
Roger. With this merges #190 and #192 are fixed :)

**Comment by Foggalong** [comment]
Gonna do a little bit of testing with these fixes, and the a commit which adds the "install both in the same place" clarification to the README and in that commit I'll close those issues :)

**Comment by pgera** [comment]
I don't see these icons in Unity's dash search any more.

**Comment by dirtydancing** [comment]
@pgera Try an icon cache update (assuming you have Numix base installed globally):

`sudo gtk-update-icon-cache /usr/share/icons/Numix`

If you see no immediate change, to keep it simple: restart your machine. Any luck? :)

**Comment by pgera** [comment]
@dirtydancing , No luck. Tried both.
screenshot from 2015-07-10 23 53 47

**Comment by wa4557** [comment]
Close the dash; change to another icon theme (doesn't matter which one); change back to Numix; run `killall unity-scope-home`. 

I cannot reproduce your issue :(

**Comment by wa4557** [comment]
what does `notify-send test -i google-chrome` give?

**Comment by dirtydancing** [comment]
Just in case: try a forced icon cache update: `sudo gtk-update-icon-cache -f /usr/share/icons/Numix`

**Comment by pgera** [comment]
Force update did it. Thanks!

**Comment by dirtydancing** [comment]
:+1:

**Pull request merged**
