### PR TITLE
Fixes #362

### LINKED ISSUE #362: Request: Mimetype: application/x-subrip
Name: **SubRip subtitles**
Mimetype: **application/x-subrip**
Possible extensions: **.srt**

Description: **File responsible for provide subtitles for movies/videos** (very common for non-English speakers)
image
Target File name: application-x-subrip.svg

### PR DESCRIPTION
**Pull request by hlechner**
#362 
For some reason the github preview doesn't show the properly icon.

@palob Do you know if I need to modify something else?

### CODE REVIEW

**Comment by Foggalong** [comment]
Make sure you put any straight parts and align them to grid :)

**Comment by hlechner** [comment]
Actually I've no idea how to do that :P

I thought that I've aligned it before. So I need to learn it, probably I'll spend some time before finish it

**Comment by Foggalong** [comment]
Press `#` to make sure the grid is showing, then press `F2` and click on the shape you want to align. You'll see little dots called nodes appear. Just make sure that the outline of the shape (that isn't a corner) between two nodes is following the lines of the grid :)

**Comment by hlechner** [comment]
Could you let me know if I made it right in the 48x48? so I can apply to the rest

**Comment by palob** [comment]
For the preview showing broken icons, I've had this before when editing or using elements from existing Numix Circle icons (presumably the ones which already existed before the base plate conversion). I haven't understand what's casuing this so far.

**Comment by Foggalong** [comment]
@hlechner yup, that's aligned right :)

**Comment by hlechner** [comment]
Done, but should be an easier way to do that than edit one by one :P

**Comment by palob** [comment]
Yep, everything's aligned+centered now :+1:

**Comment by Foggalong** [comment]
That's the downside of doing icons for every size, and why we only do 48px for Numix Circle :)

**Pull request merged**
