### PR TITLE
Fixes #473

### LINKED ISSUE #473: Enhance notification icons
Issue concerning all *buntu distributions.
This issue only makes sense if most of the current pull-requests (esp. #468) are merged and #472 is addressed:
The current notification icons are basically scaled up status icons. I think it would be better if icons from `devices` would be used, because that would mean that they are less grey and dull. An excpetion for that would be the sound notification and brightness notifications because they are somehow special considering their placement and greyish progress bar.

So my idea would be something like this:

bildschirmfoto vom 2015-04-29 14 17 39

- Symlink battery icons from devices to notifications (only works if and when #452 is merged). 
- Symlink `network-wireless` in `devices` to `nm-device-wwan` in `notifications`. 
- Symlink `nm-device-wired` in `devices` to `nm-device-wired` in `notifications` (the icon will probably look different in the future, see #468).
- If #472 is addressed symlink `nm-device-wireless`in `devices` to `notifications` (if #472 is not addressed do that as well, but change the design of `notification-network-wireless-disconnected`)
- If #468 is merged (that's the reason the symlink is broken currently) symlink `network-wired-disconnected` to `notification-network-ethernet-disconnected` and 
- design two new icons for `notification-network-wireless-disconnected` and `notification-gsm-disconnected` (my suggested icons can be seen in the screenshot). 

This generally leads to nicer notifications and solves the bug, that Xubuntu takes `nm-device-wired` and `nm-device-wireless` from `devices` instead of `notifications` for its notifications

### PR DESCRIPTION
**Pull request by wa4557**
Since we have now new and pretty devices icons the notifications icon for ethernet needs to be made consistent. Fixes #473 (kind of :)

### CODE REVIEW

**Comment by Foggalong** [comment]
Has the other ethernet design been completely remove from everywhere else in the theme then?

**Comment by wa4557** [comment]
Almost. The symbolic icon has still the old design. Replacing the symbolic icon with a variant of this one would also fix #459 btw

**Comment by Foggalong** [comment]
Ah, feel free to add those to this request then. Kill two birds with one stone :)

**Comment by wa4557** [comment]
Will do

**Comment by wa4557** [comment]
Did

**Comment by dirtydancing** [comment]
@wa4557 As to the "symbolic"-named icon: Please note that the 16x16 icon has been designed for the fixed size 16x16 directory, not for the `scalable` directory. The icons in the `scalable` directory are somewhat different, mostly larger in relation to the canvas (e.g. also for the battery icon). So I am wondering if this design is fitting for the "symbolic"-named icon in `scalable` (from what I can tell, the design form has stayed the same?).

Maybe we will need to address this and make it more consistent with the other "symbolic"-named icons. It not checked yet, this might need testing in GNOME Shell, which is where this will be displayed.

**Comment by dirtydancing** [comment]
Here are two comparative screenshots to demonstrate what I mean:

Design before:
before

Design current:
current

As you can see, the icon is indeed to small for this purpose and breaks consistency. Given this, I would recommend to revert this change (for this single icon). The size inconsistency (not too bad imo) in GNOME Shell panel rather is a matter of the volume icon being too small. To clarify, I do think that the direction of this redesign is better also for GNOME Shell, it just needs some more attention.

**Comment by wa4557** [comment]
Yeah you're right, obviously. But it's just one icon, so another pull-request should solve that issue. Do you want/can do that? I'm a bit busy right now

**Comment by dirtydancing** [comment]
This will require some more time, because this involves the consistency of the GNOME Shell panel. I am happy to have a look into it (also into the volume icon), but this will take some time. So for the time being, I would recommend to revert this one.

**Comment by wa4557** [comment]
Cool I'll create a pull request that reverts this change in scalable.

**Pull request merged**
