### PR TITLE
A few symbolic icons from Adwaita

### PR DESCRIPTION
**Pull request by wa4557**
From #577.

EDIT: I also added a few non symbolic icons

### CODE REVIEW

**Comment by Foggalong** [comment]
@wa4557 A few of these icons aren't showing up in the GitHub render which iirc means something's wrong with the icon? They're also behaving a bit weird when opened in Inkscapes, the shapes appearing bigger than they actually why. I've had a quick play around but can't work out why :/
shot1

**Comment by wa4557** [comment]
Hmm. Cannot reproduce, for me every icon shows correctly up in github. What icon are you talking about?

**Comment by Foggalong** [comment]
Both `media-zip-symbolic` and `uninterruptible-power-supply-symbolic` are still showing up blank so I'm guessing there's a mask there too?

**Comment by wa4557** [comment]
Alright. Now it should be fixed. Did show up correctly in chrome, though, I guess you are using firefox :)

**Comment by Foggalong** [comment]
Aye, Mozilla all the way! Was it a mask problem or something else causing it?

**Comment by wa4557** [comment]
some leftover gradient definitions, should  all be gone now.

Btw: since all PR are closed now we could fix the ppa

**Pull request merged**
