### PR TITLE
Added mimetype for the R language

### PR DESCRIPTION
**Pull request by palob**
text-x-r

### CODE REVIEW

**Comment by Foggalong** [comment]
Would it be possible to incorporate the design of RLogo.svg from Circle?

**Comment by palob** [comment]
It is the *R* from Circle. So you're talking about the lines? Might be doable for 32px+.

**Comment by Foggalong** [comment]
Yeah, the swirly lines :)

**Comment by palob** [comment]
A few quick drafts:
text-x-r-lines
text-x-r-lines3
text-x-r-lines5
text-x-r-lines32
text-x-r-lines64

Didn't turn out quite as well as I thought it could. Looks a bit busy, doesn't it?

**Comment by Ghokun** [comment]
How would it look like without the R letter, just with the ellipsis.

**Comment by Foggalong** [comment]
It would look unrecognisable as an R icon :P That first draft, how would it look if the symbol was right 1px and down ~2px?

**Comment by palob** [comment]
text-x-r-lines0

**Comment by Foggalong** [comment]
I really like that :D

**Comment by palob** [comment]
OK, let's see how it projects to other sizes.

**Comment by Foggalong** [comment]
Sure thing :)

**Comment by palob** [comment]
plain
swirl

Plain *R* for 16, *R+ellipsis* for bigger sizes?

**Comment by Foggalong** [comment]
I think you can probably get away with the swirl for all sizes. A niche enough icon that those needing it will recognise it

**Comment by palob** [comment]
Swirls are up :)

**Pull request merged**
