### PR TITLE
create a symlink for edit-clear-all

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This icon is used in Latexilla(LaTex editor)

### CODE REVIEW

**Comment by Foggalong** [comment]
TeXMaker masterrace :rotating_light:

**Comment by bil-elmoussaoui** [comment]
I'm using it a lot those days to write my lab reports! i'm going to make it look numixy

**Comment by palob** [comment]
Ouch, I've had this in #850 already. Will remove it from there.

**Comment by bil-elmoussaoui** [comment]
@palob sorry didn't see it :/

**Pull request merged**
