### PR TITLE
More chronometer action icons

### PR DESCRIPTION
**Pull request by palob**
From the breeze theme.
chronometer-icons

### CODE REVIEW

**Comment by wa4557** [comment]
Since you are doing so much breeze icons lately I'm trying right now to add the missing breeze icons to the kde issue. Next week I might find some time to contribute icons again :)

**Comment by wa4557** [comment]
Yeah I don't know if we should do that :( the number of missing icons is 2801...

**Comment by palob** [comment]
Much appreciated :) By the way Oxygen will be [developed further on](https://kdeonlinux.wordpress.com/2015/11/08/breeze-oxygen-and-framework/) as ``oxygen-icons5``.

I've done some testing with Plasma 5 lately and Numix icon look pretty slick there.

**Comment by palob** [comment]
Ooof! Hmm, I only see a total number of 1080 files in ``actions/22`` there.

**Comment by wa4557** [comment]
So you suggest to only add the action icons?

**Comment by palob** [comment]
As far as I can see the 2801 icons can't originate from non-action icons. 
breeze is like 85% action icons.

**Comment by wa4557** [comment]
I'm taking the icons from https://github.com/NitruxSA/breeze-icon-theme/. Is this the right place?

**Comment by palob** [comment]
Currently I'm examining the installed theme from the Arch repos.
I've posted a link in #580 to the 5.4.2 release version. 
Maybe there was a big contribution meanwhile?

**Comment by wa4557** [comment]
Ok I was wrong about that. Compared wrongly, I'll add the icons right away :)

BTW: If Numix comes to KDE more complete Plasma 5 might be worth considering, looks pretty fine imo

**Comment by palob** [comment]
Unfortunately there's a (hardly fixable) little issue with out-of-place Numix Circle icons in Plasma (not as out of place as in say Evolution however).

**Comment by palob** [comment]
Browsing breeze's LibreOffice theme.... wtf how many icons does LO use?

**Comment by wa4557** [comment]
That was exactly the problem, I compared the libreoffice icons as well, but I guess this is another kind of issue. 

Ok the correct number is now 596 icons, excluding the ones already reported in that issue. I hope a lot of them are symlinks ...

**Comment by wa4557** [comment]
Ok done

**Comment by palob** [comment]
:+1: Thanks!

**Pull request merged**
