### PR TITLE
more symlinks for humanity

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Added symlinks for #826  : 
 - stock_music-library.svg
 - cab_extract.svg
 - application-install.svg
 - audio-volume-muted-blocked-panel.svg
 - dialog-info.svg
 - gnome-fs-bookmark-missing.svg
 - gnome-fs-bookmark.svg
 - gtk-dialog-warning-panel.svg
 - messagebox_info.svg
 - stock_bookmark.svg
 - stock_dialog-error.svg

I removed this symlink : 
 - gnome-fs-bookmark-missing 

as it was symlinked in places (it's a status icon)  and re symlinked it to bookmark-missing

### CODE REVIEW

**Comment by palob** [comment]
There's no removal in your commits. Anyway, as far as I can see it doesn't matter where an icon is placed.

**Comment by bil-elmoussaoui** [comment]
@palob thanks! i removed the unneeded symlinks and reverted the new symlinks!

**Comment by Foggalong** [comment]
@bil-elmoussaoui does that need doing in all sizes, not just 48?

**Comment by bil-elmoussaoui** [comment]
Those symlinks were only in 48x48

**Comment by Foggalong** [comment]
When I search via file finder it's showing up for every size

**Comment by bil-elmoussaoui** [comment]
I will check this right now

**Comment by bil-elmoussaoui** [comment]
@Foggalong can you merge this first #851 so i can fix the symlinks ?

**Comment by Foggalong** [comment]
Done :+1:

**Comment by bil-elmoussaoui** [comment]
I will close this and open a new one ;)

**Comment by Foggalong** [comment]
No problem :)

**Pull request closed without merging**
