### PR TITLE
Adds skype status icons

### PR DESCRIPTION
**Pull request by wa4557**
The skype icons from #613

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Just to be sure that everything works fine, did you tried those icons with HardcodeTray-fixer?

**Comment by wa4557** [comment]
Not yet

**Comment by bil-elmoussaoui** [comment]
Just to mention that the issue in HardcodeTray-Fixer is fixed and everything's Numix!

**Comment by wa4557** [comment]
Screenshot showing skype using Numix icon (leftmost) 

unbenannt

**Pull request merged**
