### PR TITLE
ROMs mimetypes - Fixes #879

### LINKED ISSUE #879: Mimetypes: ROM files (consoles)
**Description:** There are some specific mimetypes for some ROM files of consoles that it's listed below:

image

Nintendo:
- [x] **[NES](https://en.wikipedia.org/wiki/Nintendo_Entertainment_System) ROM** (application/x-nes-rom) - [[nestopia.svg]](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/nestopia.svg) [<1>](http://www.clker.com/cliparts/6/c/8/5/11971195211198311825BHSPitMonkey_Old_School_Game_Controller.svg) [<2>](http://cdn.flaticon.com/svg/38/38453.svg)
- [x] **[Nintendo DS](https://en.wikipedia.org/wiki/Nintendo_DS) ROM** (application/x-nintendo-ds-rom) [<1>](http://www.pubzi.com/f/Handheld-3D-Game-System.svg)[<2>](https://upload.wikimedia.org/wikipedia/ru/4/4e/Nintendo_DS.svg)
- [x] **[Nintendo64](https://en.wikipedia.org/wiki/Nintendo_64) ROM** (application/x-n64-rom) [<1>](https://upload.wikimedia.org/wikipedia/en/0/04/Nintendo_64_Logo.svg)
- [x] **[Game Boy](https://en.wikipedia.org/wiki/Game_Boy) ROM** (application/x-gameboy-rom) [<1>](https://upload.wikimedia.org/wikipedia/commons/4/41/Gameboy.svg)
- [x] **[Game Boy Advance](https://en.wikipedia.org/wiki/Game_Boy_Advance) ROM** (application/x-gba-rom) - [[vbam.svg]](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/vbam.svg)  [[gba.svg]](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gba.svg)

Sega:
- [x] **Sega [Master System](https://en.wikipedia.org/wiki/Master_System)/[Game Gear](https://en.wikipedia.org/wiki/Sega_Game_Gear) ROM** (application/x-sms-rom)
- [x] **[Genesis](https://en.wikipedia.org/wiki/Sega_Genesis) ROM** (application/x-genesis-rom) - [[gensgs.svg]](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gensgs.svg)

### PR DESCRIPTION
**Pull request by hlechner**
imageimageimageimageimageimageimage
imageimageimageimageimageimageimage
imageimageimageimageimageimageimage
imageimageimage

Fixes #879 
Fixes hlechner/hl-numix-mime#2

Description: I choose these colors because of snes mimetype that use the same colors.

Further details: [here](https://github.com/hlechner/hl-numix-mime/issues/2)

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Nice design!! :+1:

**Comment by ChuckDaniels87** [comment]
Nice one! Surprisingly, it scales pretty well to small size icons.

**Comment by hlechner** [comment]
@Foggalong you didn't comment on this one, do you think I need to find another design or maybe change something?

**Comment by Foggalong** [comment]
This has a lot of icons in it so just haven't had time to verify it yet :)

**Comment by hlechner** [comment]
Sanity check:
```
grep -R -wi "stroke:#" * | grep -v "@2" | grep mimetypes
grep -R -wi "ellipse" * | grep -v "@2" | grep mimetypes
```
**OK**, nothing found

**Pull request merged**
