### PR TITLE
New wifi status icon

### LINKED ISSUE #330: New Wifi Status icon
The wifi status icon could do with a revamp

### PR DESCRIPTION
**Pull request by wa4557**
New wifi status icon + I added new animation and notificatio icons that fit the new design (I'm not super happy with the animation, but unfortunately bluring does not work when using linux). Fixes #330 
Now just the keyboard indicators need a new design :)

### CODE REVIEW

**Comment by Foggalong** [comment]
Yeah, the animation is a little clunky but as you say librsvg still doesn't support blur. Maybe when it does (I think support is in the works) we can come back to this and see if we can tighten it up a little bit

**Comment by wa4557** [comment]
Sure thing. I fiddled around with gradients as well, but this was even worse :)

**Comment by Foggalong** [comment]
I've been testing this most of the afternoon and it looks good to me. Happy for it to be merged?

**Comment by wa4557** [comment]
Sure. I'm finished

Joshua Fogg <notifications@github.com> schrieb am Mo., 14.09.2015, 21:57:

**Comment by Foggalong** [comment]
\O/

**Pull request merged**
