### PR TITLE
Scilab filetype icon

### LINKED ISSUE #840: Mimetype : application/x-scilab-sce (Scilab)
There's some missing icons for Scilab files! 
The mimetypes are : 

- [ ] application-x-scilab
- [ ] application-x-scilab-bin
- [ ] application-x-scilab-cos
- [ ] application-x-scilab-cosf
- [ ] application-x-scilab-dem
- [ ] application-x-scilab-graph
- [ ] application-x-scilab-sav
- [ ] application-x-scilab-sce
- [ ] application-x-scilab-sci
- [ ] application-x-scilab-sod
- [ ] application-x-scilab-tst
- [ ] application-x-scilab-xcos
- [ ] application-x-scilab-zcos

Default icon 
screenshot from 2015-11-04 14-28-30

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
Taken from numix circle icon. Part of #840

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
Is this ok or should I try with a same-color-balls version?

**Comment by wa4557** [comment]
I like it (but let's wait what other are saying) but you need to make for all the other sizes as well (16,22,24,32,64)

**Comment by ChuckDaniels87** [comment]
Symlinks?

**Comment by palob** [comment]
Being multicolour it breaks ranks but it looks rad :+1: 

No symlinks possible but you might be fine with scaling up the symbol (16>32>64, 22/27>48).
At worst you need to design it for each size.

**Comment by ChuckDaniels87** [comment]
Ok, no problem. I'll just resize and copy to all sizes directories.

**Comment by palob** [comment]
You probably need to do at least 2 distinct designs: one for the ``16xX`` sizes and one for the ``22/24/48`` sizes.

**Comment by ChuckDaniels87** [comment]
This is a bit painful. At least Scale Transform in Inkscape accept simple mathematical operations.

**Comment by palob** [comment]
Yeah, but you might run into alignment issues as 24=1.5*16 and so on. 
It's not that critical with circular symbols as your one though. 
The 16px icon might need some special attention to be recognisable.

**Comment by bil-elmoussaoui** [comment]
It would be great if you can add `sci` or `sce` like in almost all mimetype icons (Numix ones)

**Comment by palob** [comment]
Well, that's only needed if one design is used for multiple filetypes. That said, is the one you reported the only mimetype used by Scilab?

**Comment by ChuckDaniels87** [comment]
Well, rescale stuff done. Really, who thought it is a good idea create an icon size with factors 11 and 2 (22px)?

**Comment by bil-elmoussaoui** [comment]
@palob forgot those :p 
```
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-bin.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-cos.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-cosf.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-dem.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-graph.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-sav.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-sce.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-sci.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-sod.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-tst.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-xcos.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-scilab-zcos.png
```

**Comment by ChuckDaniels87** [comment]
@bil-elmoussaoui , do you mean create two different icons for each fileformat?

**Comment by bil-elmoussaoui** [comment]
@ChuckDaniels87 yes

**Comment by palob** [comment]
The work required aside, it's only possible if the letters are already present on another icons since - as far as I no - no one recalls what's the font.

**Comment by ChuckDaniels87** [comment]
My ```/etc/mime.types``` only show two:
```
applications/x-scilab                   sce,sci
applications/x-scilab-xcos           xcos
```

**Comment by hlechner** [comment]
Hey, just to help about the mimes.

Actually the nautilus uses a different way to detect the mimes instead of read the /etc/mime.types (or maybe it and something else)

For example, I have the virtualbox installed, it uses their own mime for example: virtualbox-vbox

But there is nothing on mime.types

however there is a way to check the mimetypes that is detected by nautilus/gnome:
```
gvfs-info --attributes=standard:: filename.extension
```

I downloaded a sci file from the internet and I don't have any program to use it.
here the result for me:
```
display name: scilab-contrib-toolbox_skeleton-macros-scilab_sum.sci
edit name: scilab-contrib-toolbox_skeleton-macros-scilab_sum.sci
name: scilab-contrib-toolbox_skeleton-macros-scilab_sum.sci
type: regular
size:  393
uri: file:///home/hlechner/Downloads/scilab-contrib-toolbox_skeleton-macros-scilab_sum.sci
attributes:
  standard::type: 1
  standard::name: scilab-contrib-toolbox_skeleton-macros-scilab_sum.sci
  standard::display-name: scilab-contrib-toolbox_skeleton-macros-scilab_sum.sci
  standard::edit-name: scilab-contrib-toolbox_skeleton-macros-scilab_sum.sci
  standard::copy-name: scilab-contrib-toolbox_skeleton-macros-scilab_sum.sci
  standard::icon: text-x-csrc, text-x-generic
  standard::content-type: text/x-csrc
  standard::fast-content-type: application/octet-stream
  standard::size: 393
  standard::allocated-size: 8192
  standard::symbolic-icon: text-x-csrc-symbolic, text-x-generic-symbolic, text-x-csrc, text-x-generic
```

so to me, its detecting as C file: text-x-csrc

On your system the results could be different but the ``mime.types`` doesn't help too much on these cases, my suggestion is to try the ``gvfs-info`` instead.

I hope it helps.

**Comment by ChuckDaniels87** [comment]
Well @hlechner, that is working on Nautilus and its forks. Is that working in other file-managers? I supposed that if Nautilus did not find anything with ```gvfs-info``` it would fallback into **mime.types**. However, I've found some info that suggest the opposite behaviour.

I think icon theme should stick to MIME as a standard. I'm a Gnome user but I am against of reinventing the wheel and create my own standard attitude of some devs.

**Comment by ChuckDaniels87** [comment]
Just a question about this, does gvfs-info show different output if Scilab is installed?

**Comment by palob** [comment]
@ChuckDaniels87 Yes. A base set of mimetpes is provided by the [shared-mime-info](http://freedesktop.org/wiki/Specifications/shared-mime-info-spec/) package. Installed programs can register additional types.

**Comment by wa4557** [comment]
@palob the font seems to be Encode Sans (Condensed maybe?) bolded

**Comment by palob** [comment]
It is similar but if I wasn't hallucinating some letters differ considerably. Maybe the font has seen a big redesign meanwhile?

**Comment by wa4557** [comment]
I was Not able to find a letter which is different. Maybe a few icons were aligned to grid in numix?

**Comment by Foggalong** [comment]
[See this discussion](https://github.com/numixproject/numix-icon-theme/issues/218)

**Comment by wa4557** [comment]
Well no. Open sans is completely different (Uppercase G for example) https://www.google.com/fonts/specimen/Open+Sans. It really is the Ubuntu font

**Comment by Foggalong** [comment]
But yeah - whatever the font was (probably Ubuntu) it's been seriously warped over time to align to grid in the various sizes. Since before I joined Numix a few years ago we've just copied and pasted the required letters from other images

**Comment by palob** [comment]
It's **Ubuntu Mono**, bold.

**Comment by Foggalong** [comment]
:+1:

**Comment by Foggalong** [comment]
@ChuckDaniels87 I like what you were going for with the icon but I'm not sure we can merge it because it's so different :(

**Comment by ChuckDaniels87** [comment]
What about lighter background and solid red color for all circles?

**Comment by palob** [comment]
That would be more in line, however the only icons without white or grey symbol are ``text-x-iptables`` and ``application-mathematica`` (this one even uses 2 colours for the symbol).

How about white dots on a dark blue background like on http://www.scilab.org/?

**Comment by ChuckDaniels87** [comment]
That is strange. Scilab's icon is red, white and black, in contrast, Scilab's website is blue and white. Well, I think I'll try white/grey on redish background.

**Comment by ChuckDaniels87** [comment]
This is the new icon:
mimetype


Ok, I've got some questions: 

* Why 24px and 48px icon are not scaled from 16px? Their size is 22x16 and 46x36. They could be scaled from 16px with *1'5x* and *3x* scale factor.

* Why 32px and 64px are not scaled from 16px icon? They're *2x* and *4x* scale factor. Additionally, *fold effect nodes* are not aligned to the grid in 32px icons.

**Comment by palob** [comment]
Usually in order to be recognisable the 16px icon has the symbol bigger (and sometimes oddly aligned) in relation to the sheet.

If the symbol doesn't look too big on 32px/64px you can scale up 16>32>64.

22/24/48 are designed seperatley since the 1.5x scaling would introduce misalignments.
It might not be that critical for your mimetype icon without any straight lines.


That said, looking at your above 64px draft that might be too many circles for 16/22/24px. 
Is it recognisable?

**Comment by palob** [comment]
What do you mean by *fold effect*? The dog ears? As far I can see they're aligned. If not it's a bug.

**Comment by ChuckDaniels87** [comment]
Check rounded part of doggy ear. All 32px icons I've checked (`application-archive-zip`, `application-x-blender`,...) got these nodes out of the grid. Other size icons got all nodes in grid intersections.

captura de pantalla de 2015-11-22 18-54-50

**Comment by palob** [comment]
Same for the other 3 edges and 16px, 64px. It isn't that crucial though as it doesn't cause blurriness.

**Comment by Foggalong** [comment]
This design is much better, thanks :)

**Comment by bil-elmoussaoui** [comment]
Can you add the extension for larger sizes? Awesome work!!

**Comment by Foggalong** [comment]
Extension names are only needed if there are multiple versions of the same type though?

**Comment by bil-elmoussaoui** [comment]
They are, i updated the issue

**Comment by Foggalong** [comment]
Since it doesn't seem like @ChuckDaniels87 will be adding them to this one I've switched it so when this merge is pulled the original issue won't be closed, just one item ticked off :)

**Comment by palob** [comment]
So the other mimetypes can be symlinks for now, extensions as enhancement.

**Comment by bil-elmoussaoui** [comment]
Yes i'm okay for a symlink at the moment :)

**Comment by ChuckDaniels87** [comment]
Sorry @bil-elmoussaoui, I'm quite busy at work right now to make all those icons. I think symlinks could be nice by now. :wink:

**Pull request merged**
