### PR TITLE
color fixes (555555 and 888888)

### PR DESCRIPTION
**Pull request by hlechner**
Related to #959 

Changed to ``#555555``:
```
ascii - 								      32 [#545454] / 48 [#555555] / 64 [#515151]
font - 			16 [#545454] / 24 [#545454] / 32 [#545454] / 48 [#555555] / 64 [#515151]
octet-stream - 	16 [#545454] / 24 [#545454] / 32 [#545454] / 48 [#555555] / 64 [#515151]
script-blank -	16 [#545454] / 24 [#545454] / 32 [#545454] / 48 [#555555] / 64 [#515151]
```

Changed to ``#888888``:
```
document - 			16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888/#555555] / 64 [#878787]
document-template - 16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888/#555555] / 64 [#878787]
executable - 		16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
text - 				16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
text-template -		16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
cd-image - 			16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
x-desktop -			16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
trash -				16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
x-makefile -		16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
x-changelog -		16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
x-copying - 		16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
xml - 				16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
x-readme -			16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
x-script -			16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
unknown -			16 [#888888] / 24 [#888888] / 32 [#888888] / 48 [#888888] / 64 [#878787]
```

### CODE REVIEW

**Comment by Foggalong** [comment]
I'm confused - why has this added 1300 new lines of code?

**Comment by hlechner** [comment]
It's because I've manually opened the files with Inkscape made changes and saved it instead of change it by shell script.

For example:
``[application-ascii.svg] 14 lines 6.06 KB -> 91 lines 6.92 KB``

As you can see the size still similar but so much more lines. It's because this format doesn't define the most of things in the same line, probably it was created by other software (no-inkscape) or an old version of inkscape.

You can found some renaming old svg like application-ascii.svg in numix icon theme.

**Comment by palob** [comment]
The SVG cleaning script has been run on Numix base in the past. So all edited files get the cruft back.

**Comment by hlechner** [comment]
@palob, Then I think this Pull Request is useless. Should I close it?

**Comment by palob** [comment]
I was just explaining where the lines came from.
It might be a good idea to run the cleaning script again anyway - currently it saves about 45 MB.

**Comment by wa4557** [comment]
I'm currently trying to get rid of all the `clipPath` tags in Numix. while doing this I will also apply the svgclean script to all icons. This means that additional lines now are not that problematic...

**Comment by Foggalong** [comment]
Ah, thanks @wa4557 :)

**Pull request merged**
