### PR TITLE
changing the spotify-client name to spotify-indicator

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Well, we have to change the indicator icon name to ```spotify-indicator``` to avoid some conflicts with the application icon name in Numix Circle ```spotify-client.svg``` in ```scalable``` folder

### CODE REVIEW

**Comment by Foggalong** [comment]
Symlinks, not moves :P

**Comment by bil-elmoussaoui** [comment]
My repo is such a huge mess, is it possible to remove it and fork again? :P

**Comment by Foggalong** [comment]
Yeah :) Go to the repos settings for your fork, scroll down to the dangerzone, click delete. I'd recommend learning how to use branches for developing multiple forks at the same time

**Comment by bil-elmoussaoui** [comment]
Thanks i will open a new PR , sorry for the mess

**Comment by Foggalong** [comment]
Not a problem! Thanks for contributing :)

**Pull request closed without merging**
