### PR TITLE
Btsync-gui status icons

### PR DESCRIPTION
**Pull request by wa4557**
The 22x22/status part of #292. The other ones are not necessary imo (44x44/status wtf?) and the 48x48/apps icon should be covered in circle.

### CODE REVIEW

**Comment by Foggalong** [comment]
Yeah, just 22px is fine. I have no idea where 44px came from, I've seen it literally no where else.

**Comment by wa4557** [comment]
I know, see #368 :) I'll add them of course asap

**Comment by Foggalong** [comment]
Ah, I see :D keep up the great work, it's much appreciated

**Comment by wa4557** [comment]
Sure thing, give me two more days and the status icons are as perfect as they can get :D

**Comment by wa4557** [comment]
@Foggalong Should be fine now

**Pull request merged**
