### PR TITLE
Adds gtk-orientation-* icons

### PR DESCRIPTION
**Pull request by wa4557**
Four more icons from #315

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Can you symlink those icons too? that will fix 4 icons in #437 
capture du 2015-06-06 15 59 59

**Comment by wa4557** [comment]
Well, not with those icons. They are completely different. There are however icons currently in Numix that resemble the icons you posted

**Comment by bil-elmoussaoui** [comment]
Ah those icons do already exists, sorry :P

**Comment by wa4557** [comment]
Yeah except `object-rotate` but that's just a symlink :)

**Pull request merged**
