### PR TITLE
nm-applet compatible vpn connecting animation.

### PR DESCRIPTION
**Pull request by jrb**
I put together a new set of animations for nm-vpn-connecting, using the existing nm-vpn-lock with varying opacity. This appears to resolve the vpn related aspects of #1025. 

I'm also putting together a version of nm-tech-* which moves the access tech indicator to the left of the signal indicator, and sets nm-wwan-tower to completely transparent. I'll open a PR for those if this is well received.

### CODE REVIEW

**Comment by wa4557** [comment]
Wait there are nm-tech Icons in numix already. Maybe we need to move them to the left side though

**Comment by wa4557** [comment]
Your PR is alos problematic, because of the same issues raised in #1025. On ubuntu this leads to a situation like this:
unbenannt

we have to decide what we want to fix. XFCE and Unity/GNOME is obviously not possible

**Comment by jrb** [comment]
Yes, sorry, that's all I meant. I was just going to flip all the current tech icons from bottom right to bottom left, so they would avoid the VPN icons. It looks like the LTE access icon is currently missing, so that may need to be added.

**Comment by wa4557** [comment]
Isn't there also a 4G icon (i.e. LTE?)

**Comment by jrb** [comment]
Ah, that behavior in Unity/Gnome is unfortunate. For what it's worth, I'm in Mate, not Xfce, and see the Wifi icon with VPN connecting overlaid. Maybe the way to go is an overlay theme that depends on Numix and overrides parts of nm-*

There is a 4G icon, but LTE is an independent tech in NM. I suppose a symlink is sufficient. I want to say 4G gets used for WiMax connections while LTE gets used for LTE.

**Comment by wa4557** [comment]
But an overlay of WiFi icon with von Lock is fine, isn't it? The Problem in #1025 is that the wired icon is overlayed

**Comment by jrb** [comment]
I think the base image is the wired icon, with the vpn connecting animation layered on top. Because vpn connecting animation is white, and makes use of transparency, the solid 'wired' icon appears to be on top.

After looking more closely at the image in #1025, you're right. This PR would only partially resolve the issue, as the positioning of the lock itself conflicts with the wired icon.

I'm not sure how this would be resolved short of either moving the lock or altering the wired image. :-/

**Comment by jrb** [comment]
A bit more digging through the network-manager-applet source makes it look like this "Gnome/Unity vs XFCE/Mate problem is related to use of libindicate on the Gnome/Unity side, and an old school status icon for XFCE/Mate. 

This PR can probably be closed. :-/ Thanks for your help!

**Comment by wa4557** [comment]
Well let's hope xfce and mate change to libindicate as well at some point...

**Pull request closed without merging**
