### PR TITLE
A few symbolic icons from Adwaita

### PR DESCRIPTION
**Pull request by wa4557**
A few from #577

### CODE REVIEW

**Comment by Foggalong** [comment]
@wa4557 According to the original issue, in `media-playlist-consecutive-symbolic-rtl` the `-rtl` should come before the `-symbolic` not after.

**Comment by wa4557** [comment]
I have actually both in my current Adwaita installation ...

**Comment by Foggalong** [comment]
The one you've just commited is a different order again - is that order also present in your installation? For clarification `media-playlist-consecutive-rtl-symbolic` was from the original issue, `media-playlist-consecutive-symbolic-rtl` is one you added in this pulls original commit, and `media-playlist-rtl-consecutive` (with no `-symbolic`) is the one added in the second commit of this pull.

**Comment by wa4557** [comment]
Oh sorry, the `-symbolic` should be there of course. 
So we need `media-playlist-consecutive-rtl-symbolic` and `media-playlist-rtl-consecutive`

**Comment by Foggalong** [comment]
Cool, so it's just `media-playlist-consecutive-rtl-symbolic` that's missing now?

**Comment by wa4557** [comment]
There are definitely too many hyphens there. The one we need are `consecutive-rtl-symbolic` and `consecutive-symbolic-rtl`

**Comment by Foggalong** [comment]
Oh right! Sorry, I misunderstood. Thanks :+1:

**Pull request merged**
